import {NextResponse} from "next/server";
import {z} from "zod";
import {db} from "@/lib/db";
import {requireRole} from "@/lib/auth";
import {writeAudit} from "@/lib/audit";
import {apiError} from "@/lib/api-error";
const schema=z.object({
 code:z.string().trim().min(1).max(60).optional(),barcode:z.string().trim().max(60).nullable().optional(),description:z.string().trim().min(2).max(200).optional(),brand:z.string().trim().max(80).nullable().optional(),model:z.string().trim().max(120).nullable().optional(),color:z.string().trim().max(80).nullable().optional(),frameSize:z.string().trim().max(30).nullable().optional(),lensWidth:z.coerce.number().int().min(0).max(200).nullable().optional(),bridgeWidth:z.coerce.number().int().min(0).max(200).nullable().optional(),templeLength:z.coerce.number().int().min(0).max(250).nullable().optional(),material:z.string().trim().max(80).nullable().optional(),frameShape:z.string().trim().max(80).nullable().optional(),photoData:z.string().max(1500000).nullable().optional(),
 unit:z.string().trim().min(1).max(20).optional(),cost:z.coerce.number().min(0).optional(),salePrice:z.coerce.number().min(0).optional(),minimumStock:z.coerce.number().min(0).optional(),stockControlled:z.boolean().optional(),
 categoryId:z.string().nullable().optional(),supplierId:z.string().nullable().optional(),ncm:z.string().max(20).nullable().optional(),cest:z.string().max(20).nullable().optional(),
 cfop:z.string().max(10).nullable().optional(),origin:z.string().max(10).nullable().optional(),taxCode:z.string().max(30).nullable().optional(),photoData:z.string().max(1500000).nullable().optional(),active:z.boolean().optional()
});
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{await requireRole(["ADMIN","GERENTE","VENDEDOR","LABORATORIO"]);const {id}=await params;const p=await db.product.findUnique({where:{id},include:{category:true,supplier:true,lots:{where:{archived:false}}}});if(!p)return NextResponse.json({error:"Produto não encontrado."},{status:404});return NextResponse.json(p);}catch(e){return apiError(e,"Não foi possível carregar o produto.");}}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await requireRole(["ADMIN","GERENTE"]);const {id}=await params;const b=schema.parse(await req.json());const p=await db.$transaction(async tx=>{const current=await tx.product.findUnique({where:{id}});if(!current)throw new Error("PRODUCT_NOT_FOUND");if(b.categoryId&&!await tx.category.findUnique({where:{id:b.categoryId,active:true}}))throw new Error("CATEGORY_NOT_FOUND");if(b.supplierId&&!await tx.supplier.findUnique({where:{id:b.supplierId,active:true}}))throw new Error("SUPPLIER_NOT_FOUND");const x=await tx.product.update({where:{id},data:{...b,barcode:b.barcode||undefined,categoryId:b.categoryId===null?null:b.categoryId,supplierId:b.supplierId===null?null:b.supplierId,ncm:b.ncm||undefined,cest:b.cest||undefined,cfop:b.cfop||undefined,origin:b.origin||undefined,taxCode:b.taxCode||undefined}});await writeAudit(tx,{action:"UPDATE",entity:"Product",entityId:id,userId:actor.id,metadata:{fields:Object.keys(b)}});return x;});return NextResponse.json(p);}catch(e){if(e instanceof z.ZodError)return NextResponse.json({error:"Dados do produto inválidos."},{status:422});if(e instanceof Error&&e.message==="PRODUCT_NOT_FOUND")return NextResponse.json({error:"Produto não encontrado."},{status:404});if(e instanceof Error&&(e.message==="CATEGORY_NOT_FOUND"||e.message==="SUPPLIER_NOT_FOUND"))return NextResponse.json({error:e.message==="CATEGORY_NOT_FOUND"?"Categoria não encontrada.":"Fornecedor não encontrado."},{status:404});return apiError(e,"Não foi possível atualizar o produto.");}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await requireRole(["ADMIN","GERENTE"]);const {id}=await params;const x=await db.$transaction(async tx=>{const current=await tx.product.findUnique({where:{id}});if(!current)throw new Error("PRODUCT_NOT_FOUND");const p=await tx.product.update({where:{id},data:{active:false}});await writeAudit(tx,{action:"ARCHIVE",entity:"Product",entityId:id,userId:actor.id,metadata:{code:current.code}});return p;});return NextResponse.json({ok:true,product:x});}catch(e){if(e instanceof Error&&e.message==="PRODUCT_NOT_FOUND")return NextResponse.json({error:"Produto não encontrado."},{status:404});return apiError(e,"Não foi possível arquivar o produto.");}}
