"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import { effectivePermissions } from "@/lib/permissions";

type Settings=Record<string,any>;
type User={id:string;name:string;email:string;mbEmail:string|null;role:string;active:boolean;lastLoginAt:string|null;permissions:Record<string,boolean>|null};
type FiscalConfig={id?:string;legalName:string|null;tradeName:string|null;cnpj:string|null;stateRegistration:string|null;municipalRegistration:string|null;uf:string;city:string|null;taxRegime:string;integrationMode:"NFF"|"NFAE_SAT"|"PAF_NFCE"|"MANUAL";series:string|null;environment:"HOMOLOGACAO"|"PRODUCAO";secretReference:string|null;certificateType:string|null;certificateExpiresAt:string|null;certificateAuthority:string|null;certificateLastCheckedAt:string|null;active:boolean};
const roles:Record<string,string>={ADMIN:"Administrador",GERENTE:"Gerente",VENDEDOR:"Vendedor",FINANCEIRO:"Financeiro",LABORATORIO:"Laboratório"};
const keys=["tradeName","legalName","document","phone","whatsapp","email","street","number","complement","district","city","state","postalCode","timezone","currency"];
const labels:Record<string,string>={tradeName:"Nome fantasia",legalName:"Razão social",document:"CNPJ/CPF",phone:"Telefone",whatsapp:"WhatsApp",email:"E-mail",street:"Rua",number:"Número",complement:"Complemento",district:"Bairro",city:"Cidade",state:"UF",postalCode:"CEP",timezone:"Fuso horário",currency:"Moeda"};
const actions=[["Nova venda","/vendas","Abrir PDV"],["Novo cliente","/clientes","Cadastrar cliente"],["Novo pedido","/pedidos","Abrir pedido"],["Financeiro","/financeiro","Centro financeiro"],["Relatórios","/relatorios","Análises e auditoria"],["Estoque","/estoque","Controle de estoque"]];
const permissionGroups=[{title:"Operação",items:[["dashboard","Dashboard"],["agenda","Agenda"],["clientes","Clientes"],["receitas","Receitas"],["orcamentos","Orçamentos"],["pedidos","Pedidos"],["laboratorio","Laboratório"]]},{title:"Patrimônio",items:[["produtos","Produtos"],["estoque","Estoque"],["fornecedores","Fornecedores"]]},{title:"Gestão",items:[["vendas","Vendas"],["financeiro","Financeiro"],["relatorios","Relatórios"]]},{title:"Administração",items:[["configuracoes","Configurações"],["usuarios","Usuários e perfis"],["auditoria","Auditoria"],["migracao","Migração"]]}];


export default function Page(){
 const [settings,setSettings]=useState<Settings|null>(null),[users,setUsers]=useState<User[]>([]),[fiscal,setFiscal]=useState<FiscalConfig|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[tab,setTab]=useState("GERAL"),[selected,setSelected]=useState<string|null>(null);
 const [newUser,setNewUser]=useState({name:"",email:"",mbEmail:"",password:"",role:"VENDEDOR"}),[passwordUser,setPasswordUser]=useState<User|null>(null),[newPassword,setNewPassword]=useState(""),[showPassword,setShowPassword]=useState(false);
 async function load(){setLoading(true);setMessage("");try{const a=await fetch("/api/settings");const ad=await a.json();if(!a.ok)throw new Error(ad.error||"Não foi possível carregar as configurações.");setSettings(ad.settings);const f=await fetch("/api/fiscal/configuracao");const fd=await f.json();if(f.ok)setFiscal(fd.config);else setMessage(fd.error||"Configuração fiscal indisponível para este perfil.");const b=await fetch("/api/users");const bd=await b.json();if(b.ok)setUsers(bd.users);else setMessage(bd.error||"Usuários indisponíveis para este perfil.");}catch(e){setMessage(e instanceof Error?e.message:"Erro ao carregar configurações.");}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function verifyCertificate(){setBusy(true);try{const r=await fetch("/api/fiscal/certificado/verificar",{method:"POST"});const d=await r.json();setMessage(d.message||d.error||"Verificação concluída.");if(r.ok&&fiscal)setFiscal({...fiscal,certificateLastCheckedAt:d.checkedAt});}catch(e){setMessage(e instanceof Error?e.message:"Erro ao verificar certificado.")}finally{setBusy(false)}}
 async function saveFiscal(){if(!fiscal)return;setBusy(true);try{const r=await fetch("/api/fiscal/configuracao",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(fiscal)});const d=await r.json();setMessage(r.ok?"Configuração fiscal salva.":d.error||"Erro ao salvar configuração fiscal.");if(r.ok)setFiscal(d.config)}catch(e){setMessage(e instanceof Error?e.message:"Erro ao salvar configuração fiscal.")}finally{setBusy(false)}}
 async function save(){if(!settings)return;setBusy(true);try{const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const d=await r.json();setMessage(r.ok?"Configurações salvas.":d.error||"Erro ao salvar.");if(r.ok)setSettings(d.settings)}finally{setBusy(false)}}
 async function createUser(){setBusy(true);try{const r=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(newUser)});const d=await r.json();setMessage(r.ok?"Usuário criado.":d.error||"Erro ao criar usuário.");if(r.ok){setNewUser({name:"",email:"",mbEmail:"",password:"",role:"VENDEDOR"});await load()}}finally{setBusy(false)}}
 async function updateUser(id:string,patch:Record<string,any>){setBusy(true);try{const r=await fetch("/api/users/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});const d=await r.json();setMessage(r.ok?"Usuário atualizado.":d.error||"Erro ao atualizar usuário.");if(r.ok)setUsers(users.map(u=>u.id===id?{...u,...d.user}:u))}finally{setBusy(false)}}
 async function deleteUser(u:User){
  if(u.role==="ADMIN"&&u.active&&users.filter(x=>x.role==="ADMIN"&&x.active).length<=1){setMessage("O sistema precisa manter pelo menos um administrador ativo.");return}
  if(!window.confirm(`Excluir o usuário "${u.name}"? Esta ação remove o acesso do usuário. Se houver vendas, pedidos ou orçamentos vinculados, a exclusão será bloqueada para preservar o histórico.`))return;
  setBusy(true);
  try{
    const r=await fetch("/api/users/"+u.id,{method:"DELETE"});
    const d=await r.json();
    setMessage(r.ok?"Usuário excluído.":d.error||"Não foi possível excluir o usuário.");
    if(r.ok){
      if(selected===u.id)setSelected(null);
      if(passwordUser?.id===u.id)setPasswordUser(null);
      await load();
    }
  }finally{setBusy(false)}
}
 async function changePassword(){if(!passwordUser)return;if(newPassword.length<8){setMessage("A senha deve ter pelo menos 8 caracteres.");return}setBusy(true);try{const r=await fetch("/api/users/"+passwordUser.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:newPassword})});const d=await r.json();setMessage(r.ok?"Senha alterada com sucesso.":d.error||"Não foi possível alterar a senha.");if(r.ok){setNewPassword("");setPasswordUser(null);setShowPassword(false)}}finally{setBusy(false)}}
 function hasAccess(u:User,key:string){return effectivePermissions(u.role,u.permissions)[key]!==false}
 function setPermission(u:User,key:string,allowed:boolean){updateUser(u.id,{permissions:{...(u.permissions||{}),[key]:allowed}})}
 function resetPermissions(u:User){updateUser(u.id,{permissions:{}})}
 function handleLogo(file:File|null){if(!file)return;if(!file.type.startsWith("image/")){setMessage("Selecione uma imagem PNG, JPG, WEBP ou SVG.");return}if(file.size>1000000){setMessage("A logo deve ter no máximo 1 MB.");return}const reader=new FileReader();reader.onload=()=>setSettings((s)=>s?{...s,logoData:String(reader.result)}:s);reader.readAsDataURL(file)}
 const configured=useMemo(()=>settings?keys.filter(k=>settings[k]).length:0,[settings]);
 const systemStatus=useMemo(()=>({operational:17,configured,missing:Math.max(0,keys.length-configured)}),[configured]);
 const currentUser=users.find(u=>u.id===selected)||null;
 if(loading)return <section className="page"><div className="panel" style={{padding:20}}>Carregando centro de comando...</div></section>;
 if(!settings)return <section className="page"><div className="page-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Centro de comando</h1></div></div><div className="panel" style={{padding:20}}><strong>Não autenticado.</strong><p style={{marginTop:6,color:"var(--muted)"}}>{message}</p><button className="secondary" style={{marginTop:12}} onClick={load}>Tentar novamente</button></div></section>;
 return <section className="page settings-page">
  <div className="page-heading settings-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Centro de comando</h1><p>Configuração central do MB Óptica Gestão Inteligente.</p></div><div className="settings-status"><b>● Sistema operacional</b><span>{systemStatus.operational} módulos operacionais · {systemStatus.missing} parâmetros cadastrais pendentes</span></div></div>
  {message&&<div className="panel settings-message">{message}</div>}
  <div className="settings-actions">{actions.map(([title,href,sub])=><Link key={href} href={href} className="settings-action"><b>+ {title}</b><span>{sub}</span></Link>)}</div>
  <div className="settings-tabs">{[["GERAL","Geral"],["USUARIOS","Usuários e perfis"],["OPERACAO","Operação"],["FISCAL","Fiscal"],["FINANCEIRO","Financeiro"],["SEGURANCA","Segurança"],["SISTEMA","Sistema"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==="GERAL"&&<><div className="settings-grid">
    <div className="panel"><div className="panel-heading"><div><h2>Identidade da óptica</h2><p>Dados usados em documentos, impressões e comunicações.</p></div><button className="primary" disabled={busy} onClick={save}>Salvar alterações</button></div><div className="logo-settings"><div className="logo-preview">{settings.logoData?<img src={settings.logoData} alt="Logo da óptica"/>:<span>MB</span>}</div><div><b>Logo da óptica</b><p>PNG, JPG, WEBP ou SVG · até 1 MB. Será usada na identidade do sistema e poderá ser aproveitada em documentos.</p><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>handleLogo(e.target.files?.[0]||null)}/>{settings.logoData&&<button className="secondary" style={{marginTop:8}} onClick={()=>setSettings({...settings,logoData:null})}>Remover logo</button>}</div></div><div className="settings-form">{keys.map(k=><label key={k}>{labels[k]}<input placeholder={labels[k]} value={settings[k]??""} onChange={e=>setSettings({...settings,[k]:e.target.value||null})}/></label>)}</div></div>
    <div className="panel"><div className="panel-heading"><div><h2>Mapa do sistema</h2><p>Áreas sob controle deste centro.</p></div></div><div className="settings-list"><div><b>Operação</b><span>Clientes, agenda, vendas, pedidos e laboratório.</span></div><div><b>Patrimônio</b><span>Produtos, estoque, fornecedores e custos.</span></div><div><b>Gestão</b><span>Financeiro, relatórios, auditoria e indicadores.</span></div><div><b>Fiscal</b><span>Preparado para configuração fiscal e documentos eletrônicos.</span></div></div></div>
  </div></>}
  {tab==="USUARIOS"&&<div className="settings-grid">
   <div className="panel"><div className="panel-heading"><div><h2>Usuários e perfis</h2><p>Crie usuários e controle o que cada pessoa pode acessar.</p></div></div><div className="settings-form user-form"><label>Nome<input value={newUser.name} onChange={e=>setNewUser({...newUser,name:e.target.value})}/></label><label>E-mail de login<input type="email" value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/></label><label>E-mail MB<input type="email" placeholder="usuario@mboptica.com.br" value={newUser.mbEmail} onChange={e=>setNewUser({...newUser,mbEmail:e.target.value})}/></label><label>Senha<input type="password" placeholder="mín. 8 caracteres" value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/></label><label>Perfil<select value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className="primary" disabled={busy} onClick={createUser}>Criar usuário</button></div><div className="table"><div className="row header"><span>Nome</span><span>E-mail de login</span><span>E-mail MB</span><span>Perfil</span><span>Status</span><span>Ações</span></div>{users.map(u=><div className="row" key={u.id}><strong>{u.name}</strong><span>{u.email}</span><span>{u.mbEmail||"—"}</span><span>{roles[u.role]??u.role}</span><span>{u.active?"Ativo":"Inativo"}</span><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="secondary" onClick={()=>setSelected(selected===u.id?null:u.id)}>{selected===u.id?"Fechar":"Permissões"}</button><button className="secondary" onClick={()=>{setPasswordUser(passwordUser?.id===u.id?null:u);setNewPassword("");setShowPassword(false)}}>{passwordUser?.id===u.id?"Fechar senha":"Alterar senha"}</button><button className="secondary" disabled={busy} style={{color:"#b42318",borderColor:"#f2b8b5"}} onClick={()=>deleteUser(u)}>Excluir</button></div></div>)}</div></div>
   <div className="panel permission-panel"><div className="panel-heading"><div><h2>{currentUser?"Permissões de "+currentUser.name:"Permissões individuais"}</h2><p>{currentUser?"O perfil define o acesso-base; aqui você pode criar restrições individuais por módulo.":"Selecione um usuário na lista para configurar."}</p></div></div>{passwordUser&&<div className="panel" style={{marginBottom:16,padding:16}}><div className="panel-heading"><div><h3 style={{margin:0}}>Alterar senha</h3><p style={{marginTop:4}}>Nova senha para {passwordUser.name}. Mínimo de 8 caracteres.</p></div></div><div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap"}}><label style={{flex:"1 1 280px"}}>Nova senha<input type={showPassword?"text":"password"} minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="Mínimo de 8 caracteres"/></label><button className="secondary" type="button" onClick={()=>setShowPassword(!showPassword)}>{showPassword?"Ocultar":"Mostrar"}</button><button className="primary" type="button" disabled={busy||newPassword.length<8} onClick={changePassword}>Salvar nova senha</button></div></div>}{currentUser?<div><div className="panel" style={{marginBottom:16,padding:16}}><div className="panel-heading"><div><h3 style={{margin:0}}>Caixa de e-mail MB</h3><p style={{marginTop:4}}>Endereço usado para envio e recebimento de mensagens da loja para este usuário.</p></div></div><div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap"}}><label style={{flex:"1 1 320px"}}>E-mail MB<input type="email" placeholder="usuario@mboptica.com.br" value={currentUser.mbEmail??""} onChange={e=>setUsers(users.map(u=>u.id===currentUser.id?{...u,mbEmail:e.target.value||null}:u))}/></label><button className="primary" type="button" disabled={busy} onClick={()=>updateUser(currentUser.id,{mbEmail:currentUser.mbEmail||null})}>Salvar e-mail MB</button></div></div><div className="permission-meta"><b>{roles[currentUser.role]||currentUser.role}</b><span>Permissões individuais prevalecem quando houver uma restrição explícita.</span><button className="secondary" disabled={busy} onClick={()=>resetPermissions(currentUser)}>Restaurar padrão do perfil</button></div>{permissionGroups.map(g=><div className="permission-group" key={g.title}><h3>{g.title}</h3>{g.items.map(([key,label])=><label key={key} className="permission-item"><span><b>{label}</b><small>{hasAccess(currentUser,key)?"Acesso permitido":"Acesso bloqueado"}</small></span><input type="checkbox" checked={hasAccess(currentUser,key)} disabled={busy||currentUser.role==="ADMIN"} onChange={e=>setPermission(currentUser,key,e.target.checked)}/></label>)}</div>)}{currentUser.role==="ADMIN"&&<p className="permission-note">Administradores mantêm acesso integral ao sistema.</p>}</div>:<div style={{padding:"20px",color:"var(--muted)"}}>Clique em <b>Permissões</b> ao lado de um usuário.</div>}</div>
  </div>}
  {tab==="OPERACAO"&&<SettingsPanel title="Operação" text="Parâmetros para o funcionamento diário da óptica." links={[["Clientes","/clientes"],["Agenda","/agenda"],["Vendas","/vendas"],["Pedidos","/pedidos"],["Laboratório","/laboratorio"],["Produtos","/produtos"],["Estoque","/estoque"],["Fornecedores","/fornecedores"]]}/>}
  {tab==="FISCAL"&&<div className="settings-grid">
   <div className="panel"><div className="panel-heading"><div><h2>Configuração fiscal</h2><p>Dados fiscais usados como base para a futura emissão eletrônica. Nesta etapa, apenas parametrizamos; nenhuma nota é transmitida.</p></div><button className="primary" disabled={busy||!fiscal} onClick={saveFiscal}>Salvar configuração fiscal</button></div>
   {fiscal&&<><div className="settings-form">
    <label>Razão social<input value={fiscal.legalName??""} onChange={e=>setFiscal({...fiscal,legalName:e.target.value||null})}/></label>
    <label>Nome fantasia<input value={fiscal.tradeName??""} onChange={e=>setFiscal({...fiscal,tradeName:e.target.value||null})}/></label>
    <label>CNPJ<input value={fiscal.cnpj??""} onChange={e=>setFiscal({...fiscal,cnpj:e.target.value||null})}/></label>
    <label>Inscrição estadual<input value={fiscal.stateRegistration??""} onChange={e=>setFiscal({...fiscal,stateRegistration:e.target.value||null})}/></label>
    <label>Inscrição municipal<input value={fiscal.municipalRegistration??""} onChange={e=>setFiscal({...fiscal,municipalRegistration:e.target.value||null})}/></label>
    <label>UF<input maxLength={2} value={fiscal.uf} onChange={e=>setFiscal({...fiscal,uf:e.target.value.toUpperCase()})}/></label>
    <label>Município<input value={fiscal.city??""} onChange={e=>setFiscal({...fiscal,city:e.target.value||null})}/></label>
    <label>Regime tributário<select value={fiscal.taxRegime} onChange={e=>setFiscal({...fiscal,taxRegime:e.target.value})}><option value="SIMEI">SIMEI</option><option value="SIMPLES_NACIONAL">Simples Nacional</option><option value="LUCRO_PRESUMIDO">Lucro Presumido</option><option value="LUCRO_REAL">Lucro Real</option></select></label>
    <label>Modo de integração<select value={fiscal.integrationMode} onChange={e=>setFiscal({...fiscal,integrationMode:e.target.value as FiscalConfig["integrationMode"]})}><option value="NFF">NFF</option><option value="NFAE_SAT">NFA-e / SAT</option><option value="PAF_NFCE">PAF-NFC-e</option><option value="MANUAL">Manual</option></select></label>
    <label>Série fiscal<input value={fiscal.series??""} onChange={e=>setFiscal({...fiscal,series:e.target.value||null})}/></label>
    <label>Ambiente<select value={fiscal.environment} onChange={e=>setFiscal({...fiscal,environment:e.target.value as FiscalConfig["environment"]})}><option value="HOMOLOGACAO">Homologação</option><option value="PRODUCAO">Produção</option></select></label>
    <label>Referência do certificado/segredo<input value={fiscal.secretReference??""} onChange={e=>setFiscal({...fiscal,secretReference:e.target.value||null})}/></label> 
    <label>Tipo do certificado<select value={fiscal.certificateType??""} onChange={e=>setFiscal({...fiscal,certificateType:e.target.value||null})}><option value="">Selecionar</option><option value="A1">A1</option><option value="A3">A3</option><option value="SE-S">SE-S (selo eletrônico)</option><option value="SE-H">SE-H (selo eletrônico)</option></select></label>
    <label>Validade do certificado<input type="date" value={fiscal.certificateExpiresAt?fiscal.certificateExpiresAt.slice(0,10):""} onChange={e=>setFiscal({...fiscal,certificateExpiresAt:e.target.value?new Date(e.target.value+"T23:59:59").toISOString():null})}/></label>
    <label>Autoridade certificadora<input value={fiscal.certificateAuthority??""} onChange={e=>setFiscal({...fiscal,certificateAuthority:e.target.value||null})}/></label>
   </div><div style={{marginTop:14,padding:14,border:"1px solid var(--border)",borderRadius:10,background:"var(--surface-2)"}}><b>Segurança</b><p style={{marginTop:6,color:"var(--muted)"}}>O MB Óptica armazena somente a referência ao segredo e os metadados do certificado. O arquivo, a chave privada e a senha não são armazenados nesta tela.</p><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",marginTop:10}}><button className="secondary" type="button" disabled={busy||!fiscal} onClick={verifyCertificate}>Verificar cadastro do certificado</button><span style={{color:"var(--muted)",fontSize:13}}>{fiscal?.certificateLastCheckedAt?"Última verificação registrada":"Ainda não verificado"}</span></div><label style={{display:"flex",alignItems:"center",gap:8,marginTop:10}}><input type="checkbox" checked={fiscal.active} onChange={e=>setFiscal({...fiscal,active:e.target.checked})}/> Configuração fiscal ativa</label></div></>}
   </div>
   <div className="panel"><div className="panel-heading"><div><h2>Estado da configuração</h2><p>Checklist da etapa 7.2.</p></div></div><div className="settings-list"><div><b>Empresa</b><span>{fiscal?.cnpj&&fiscal?.legalName?"Identificação preenchida":"Pendente: CNPJ e razão social."}</span></div><div><b>Localização</b><span>{fiscal?.uf&&fiscal?.city?"UF e município preenchidos":"Pendente: UF e município."}</span></div><div><b>Tributação</b><span>{fiscal?.taxRegime?"Regime definido":"Pendente: regime tributário."}</span></div><div><b>Integração</b><span>{fiscal?.integrationMode&&fiscal?.series?"Modo e série definidos":"Pendente: modo de integração e/ou série."}</span></div><div><b>Ambiente</b><span>{fiscal?.environment==="PRODUCAO"?"Produção selecionada — emissão ainda não é habilitada nesta etapa.":"Homologação selecionada."}</span></div><div><b>Certificado</b><span>{fiscal?.secretReference&&fiscal?.certificateType&&fiscal?.certificateExpiresAt?"Cadastro completo; verificar prontidão.":"Pendente: referência, tipo e/ou validade."}</span></div></div><div className="settings-link-grid" style={{marginTop:16}}><Link href="/relatorios">Relatórios fiscais</Link><Link href="/vendas">Vendas e documentos</Link></div></div>
  </div>}
  {tab==="FINANCEIRO"&&<SettingsPanel title="Centro financeiro" text="Parâmetros e atalhos para caixa, contas, recebimentos e pagamentos." links={[["Financeiro","/financeiro"],["Vendas","/vendas"],["Relatórios","/relatorios"]]}/>}
  {tab==="SEGURANCA"&&<SettingsPanel title="Segurança e governança" text="Controles de acesso, rastreabilidade e auditoria das operações." links={[["Usuários e perfis","/configuracoes"],["Auditoria","/relatorios"],["Migração","/migracao"]]}/>}
  {tab==="SISTEMA"&&<SettingsPanel title="Sistema e manutenção" text="Ferramentas administrativas para manutenção, integridade e evolução do MB Óptica." links={[["Relatórios","/relatorios"],["Migração","/migracao"],["Saúde do sistema","/api/health"]]}/>}
 </section>
}
function SettingsPanel({title,text,links}:{title:string;text:string;links:string[][]}){return <div className="settings-grid"><div className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>{text}</p></div></div><div className="settings-link-grid">{links.map(([label,href])=><Link key={href+label} href={href}>{label}</Link>)}</div></div><div className="panel"><div className="panel-heading"><div><h2>Governança</h2><p>Princípios do centro de comando.</p></div></div><div className="settings-list"><div><b>Rastreabilidade</b><span>Operações relevantes devem permanecer auditáveis.</span></div><div><b>Permissões</b><span>Ações administrativas respeitam o perfil do usuário.</span></div><div><b>Integridade</b><span>Dados críticos devem ser validados antes de alterações.</span></div></div></div></div>}
