"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";

type Settings=Record<string,any>;
type User={id:string;name:string;email:string;role:string;active:boolean;lastLoginAt:string|null};
const roles:Record<string,string>={ADMIN:"Administrador",GERENTE:"Gerente",VENDEDOR:"Vendedor",FINANCEIRO:"Financeiro",LABORATORIO:"Laboratório"};
const keys=["tradeName","legalName","document","phone","whatsapp","email","street","number","complement","district","city","state","postalCode","timezone","currency"];
const labels:Record<string,string>={tradeName:"Nome fantasia",legalName:"Razão social",document:"CNPJ/CPF",phone:"Telefone",whatsapp:"WhatsApp",email:"E-mail",street:"Rua",number:"Número",complement:"Complemento",district:"Bairro",city:"Cidade",state:"UF",postalCode:"CEP",timezone:"Fuso horário",currency:"Moeda"};
const actions=[["Nova venda","/vendas","Abrir PDV"],["Novo cliente","/clientes","Cadastrar cliente"],["Novo pedido","/pedidos","Abrir pedido"],["Financeiro","/financeiro","Centro financeiro"],["Relatórios","/relatorios","Análises e auditoria"],["Estoque","/estoque","Controle de estoque"]];

export default function Page(){
 const [settings,setSettings]=useState<Settings|null>(null),[users,setUsers]=useState<User[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[tab,setTab]=useState("GERAL");
 const [newUser,setNewUser]=useState({name:"",email:"",password:"",role:"VENDEDOR"});
 async function load(){setLoading(true);setMessage("");try{const a=await fetch("/api/settings");const ad=await a.json();if(!a.ok)throw new Error(ad.error||"Não foi possível carregar as configurações.");setSettings(ad.settings);const b=await fetch("/api/users");const bd=await b.json();if(b.ok)setUsers(bd.users);else setMessage(bd.error||"Usuários indisponíveis para este perfil.");}catch(e){setMessage(e instanceof Error?e.message:"Erro ao carregar configurações.");}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function save(){if(!settings)return;setBusy(true);try{const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const d=await r.json();setMessage(r.ok?"Configurações salvas.":d.error||"Erro ao salvar.");if(r.ok)setSettings(d.settings)}finally{setBusy(false)}}
 async function createUser(){setBusy(true);try{const r=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(newUser)});const d=await r.json();setMessage(r.ok?"Usuário criado.":d.error||"Erro ao criar usuário.");if(r.ok){setNewUser({name:"",email:"",password:"",role:"VENDEDOR"});await load()}}finally{setBusy(false)}}
 const configured=useMemo(()=>settings?keys.filter(k=>settings[k]).length:0,[settings]);
 if(loading)return <section className="page"><div className="panel" style={{padding:20}}>Carregando centro de comando...</div></section>;
 if(!settings)return <section className="page"><div className="page-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Centro de comando</h1><p>Configuração central do MB Óptica Gestão Inteligente.</p></div></div><div className="panel" style={{padding:20}}><strong>Não autenticado.</strong><p style={{marginTop:6,color:"var(--muted)"}}>{message}</p><button className="secondary" style={{marginTop:12}} onClick={load}>Tentar novamente</button></div></section>;
 return <section className="page settings-page">
  <div className="page-heading settings-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Centro de comando</h1><p>Configuração central do MB Óptica Gestão Inteligente.</p></div><div className="settings-status"><b>● Sistema operacional</b><span>{configured}/{keys.length} parâmetros configurados</span></div></div>
  {message&&<div className="panel settings-message">{message}</div>}
  <div className="settings-actions">{actions.map(([title,href,sub])=><Link key={href} href={href} className="settings-action"><b>+ {title}</b><span>{sub}</span></Link>)}</div>
  <div className="settings-tabs">{[["GERAL","Geral"],["USUARIOS","Usuários e perfis"],["OPERACAO","Operação"],["FISCAL","Fiscal"],["FINANCEIRO","Financeiro"],["SEGURANCA","Segurança"],["SISTEMA","Sistema"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==="GERAL"&&<><div className="settings-grid">
    <div className="panel"><div className="panel-heading"><div><h2>Identidade da óptica</h2><p>Dados usados em documentos, impressões e comunicações.</p></div><button className="primary" disabled={busy} onClick={save}>Salvar alterações</button></div><div className="settings-form">{keys.map(k=><label key={k} className={k==="tradeName"||k==="legalName"||k==="email"?"wide":""}>{labels[k]}<input placeholder={labels[k]} value={settings[k]??""} onChange={e=>setSettings({...settings,[k]:e.target.value||null})}/></label>)}</div></div>
    <div className="panel"><div className="panel-heading"><div><h2>Mapa do sistema</h2><p>Áreas sob controle deste centro.</p></div></div><div className="settings-list"><div><b>Operação</b><span>Clientes, agenda, vendas, pedidos e laboratório.</span></div><div><b>Patrimônio</b><span>Produtos, estoque, fornecedores e custos.</span></div><div><b>Gestão</b><span>Financeiro, relatórios, auditoria e indicadores.</span></div><div><b>Fiscal</b><span>Preparado para configuração fiscal e documentos eletrônicos.</span></div></div></div>
  </div><div className="settings-grid"><div className="panel"><div className="panel-heading"><div><h2>Parâmetros gerais</h2><p>Base operacional do sistema.</p></div></div><div className="settings-list"><div><b>Fuso horário</b><span>{settings.timezone||"America/Sao_Paulo"}</span></div><div><b>Moeda</b><span>{settings.currency||"BRL"} · Real brasileiro</span></div><div><b>UF principal</b><span>{settings.state||"SC"}</span></div></div></div><div className="panel"><div className="panel-heading"><div><h2>Acessos rápidos</h2><p>Atalhos para as áreas administrativas.</p></div></div><div className="settings-link-grid"><Link href="/relatorios">Auditoria e relatórios</Link><Link href="/financeiro">Centro financeiro</Link><Link href="/migracao">Migração de dados</Link><Link href="/configuracoes">Configurações</Link></div></div></div></>}
  {tab==="USUARIOS"&&<div className="panel"><div className="panel-heading"><div><h2>Usuários e perfis</h2><p>Controle de acesso operacional por função.</p></div></div><div className="settings-form user-form"><label>Nome<input value={newUser.name} onChange={e=>setNewUser({...newUser,name:e.target.value})}/></label><label>E-mail<input value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/></label><label>Senha<input type="password" placeholder="mín. 10 caracteres" value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/></label><label>Perfil<select value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className="primary" disabled={busy} onClick={createUser}>Criar usuário</button></div><div className="table"><div className="row header"><span>Nome</span><span>E-mail</span><span>Perfil</span><span>Status</span><span>Último acesso</span></div>{users.map(u=><div className="row" key={u.id}><strong>{u.name}</strong><span>{u.email}</span><span>{roles[u.role]??u.role}</span><span>{u.active?"Ativo":"Inativo"}</span><span>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString("pt-BR"):"Nunca"}</span></div>)}</div></div>}
  {tab==="OPERACAO"&&<SettingsPanel title="Operação" text="Parâmetros para o funcionamento diário da óptica." links={[["Clientes","/clientes"],["Agenda","/agenda"],["Vendas","/vendas"],["Pedidos","/pedidos"],["Laboratório","/laboratorio"],["Produtos","/produtos"],["Estoque","/estoque"],["Fornecedores","/fornecedores"]]}/>}
  {tab==="FISCAL"&&<SettingsPanel title="Centro fiscal" text="Área reservada para parametrização fiscal e acompanhamento de documentos." links={[["Vendas e documentos","/vendas"],["Relatórios","/relatorios"],["Configurações gerais","/configuracoes"]]}/>}
  {tab==="FINANCEIRO"&&<SettingsPanel title="Centro financeiro" text="Parâmetros e atalhos para caixa, contas, recebimentos e pagamentos." links={[["Financeiro","/financeiro"],["Vendas","/vendas"],["Relatórios","/relatorios"]]}/>}
  {tab==="SEGURANCA"&&<SettingsPanel title="Segurança e governança" text="Controles de acesso, rastreabilidade e auditoria das operações." links={[["Usuários e perfis","/configuracoes"],["Auditoria","/relatorios"],["Migração","/migracao"]]}/>}
  {tab==="SISTEMA"&&<SettingsPanel title="Sistema e manutenção" text="Ferramentas administrativas para manutenção, integridade e evolução do MB Óptica." links={[["Relatórios","/relatorios"],["Migração","/migracao"],["Saúde do sistema","/api/health"]]}/>}
 </section>
}
function SettingsPanel({title,text,links}:{title:string;text:string;links:string[][]}){return <div className="settings-grid"><div className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>{text}</p></div></div><div className="settings-link-grid">{links.map(([label,href])=><Link key={href+label} href={href}>{label}</Link>)}</div></div><div className="panel"><div className="panel-heading"><div><h2>Governança</h2><p>Princípios do centro de comando.</p></div></div><div className="settings-list"><div><b>Rastreabilidade</b><span>Operações relevantes devem permanecer auditáveis.</span></div><div><b>Permissões</b><span>Ações administrativas respeitam o perfil do usuário.</span></div><div><b>Integridade</b><span>Dados críticos devem ser validados antes de alterações.</span></div></div></div></div>}
