"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import { effectivePermissions } from "@/lib/permissions";

type Settings=Record<string,any>;
type User={id:string;name:string;email:string;role:string;active:boolean;lastLoginAt:string|null;permissions:Record<string,boolean>|null};
const roles:Record<string,string>={ADMIN:"Administrador",GERENTE:"Gerente",VENDEDOR:"Vendedor",FINANCEIRO:"Financeiro",LABORATORIO:"Laboratório"};
const keys=["tradeName","legalName","document","phone","whatsapp","email","street","number","complement","district","city","state","postalCode","timezone","currency"];
const labels:Record<string,string>={tradeName:"Nome fantasia",legalName:"Razão social",document:"CNPJ/CPF",phone:"Telefone",whatsapp:"WhatsApp",email:"E-mail",street:"Rua",number:"Número",complement:"Complemento",district:"Bairro",city:"Cidade",state:"UF",postalCode:"CEP",timezone:"Fuso horário",currency:"Moeda"};
const actions=[["Nova venda","/vendas","Abrir PDV"],["Novo cliente","/clientes","Cadastrar cliente"],["Novo pedido","/pedidos","Abrir pedido"],["Financeiro","/financeiro","Centro financeiro"],["Relatórios","/relatorios","Análises e auditoria"],["Estoque","/estoque","Controle de estoque"]];
const permissionGroups=[{title:"Operação",items:[["dashboard","Dashboard"],["agenda","Agenda"],["clientes","Clientes"],["receitas","Receitas"],["orcamentos","Orçamentos"],["pedidos","Pedidos"],["laboratorio","Laboratório"]]},{title:"Patrimônio",items:[["produtos","Produtos"],["estoque","Estoque"],["fornecedores","Fornecedores"]]},{title:"Gestão",items:[["vendas","Vendas"],["financeiro","Financeiro"],["relatorios","Relatórios"]]},{title:"Administração",items:[["configuracoes","Configurações"],["usuarios","Usuários e perfis"],["auditoria","Auditoria"],["migracao","Migração"]]}];


export default function Page(){
 const [settings,setSettings]=useState<Settings|null>(null),[users,setUsers]=useState<User[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[tab,setTab]=useState("GERAL"),[selected,setSelected]=useState<string|null>(null);
 const [newUser,setNewUser]=useState({name:"",email:"",password:"",role:"VENDEDOR"}),[passwordUser,setPasswordUser]=useState<User|null>(null),[newPassword,setNewPassword]=useState(""),[showPassword,setShowPassword]=useState(false);
 async function load(){setLoading(true);setMessage("");try{const a=await fetch("/api/settings");const ad=await a.json();if(!a.ok)throw new Error(ad.error||"Não foi possível carregar as configurações.");setSettings(ad.settings);const b=await fetch("/api/users");const bd=await b.json();if(b.ok)setUsers(bd.users);else setMessage(bd.error||"Usuários indisponíveis para este perfil.");}catch(e){setMessage(e instanceof Error?e.message:"Erro ao carregar configurações.");}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function save(){if(!settings)return;setBusy(true);try{const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const d=await r.json();setMessage(r.ok?"Configurações salvas.":d.error||"Erro ao salvar.");if(r.ok)setSettings(d.settings)}finally{setBusy(false)}}
 async function createUser(){setBusy(true);try{const r=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(newUser)});const d=await r.json();setMessage(r.ok?"Usuário criado.":d.error||"Erro ao criar usuário.");if(r.ok){setNewUser({name:"",email:"",password:"",role:"VENDEDOR"});await load()}}finally{setBusy(false)}}
 async function updateUser(id:string,patch:Record<string,any>){setBusy(true);try{const r=await fetch("/api/users/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});const d=await r.json();setMessage(r.ok?"Usuário atualizado.":d.error||"Erro ao atualizar usuário.");if(r.ok)setUsers(users.map(u=>u.id===id?{...u,...d.user}:u))}finally{setBusy(false)}}
 async function changePassword(){if(!passwordUser)return;if(newPassword.length<8){setMessage("A senha deve ter pelo menos 8 caracteres.");return}setBusy(true);try{const r=await fetch("/api/users/"+passwordUser.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:newPassword})});const d=await r.json();setMessage(r.ok?"Senha alterada com sucesso.":d.error||"Não foi possível alterar a senha.");if(r.ok){setNewPassword("");setPasswordUser(null);setShowPassword(false)}}finally{setBusy(false)}}
 function hasAccess(u:User,key:string){return effectivePermissions(u.role,u.permissions)[key]!==false}
 function setPermission(u:User,key:string,allowed:boolean){updateUser(u.id,{permissions:{...(u.permissions||{}),[key]:allowed}})}
 function resetPermissions(u:User){updateUser(u.id,{permissions:{}})}
 function handleLogo(file:File|null){if(!file)return;if(!file.type.startsWith("image/")){setMessage("Selecione uma imagem PNG, JPG, WEBP ou SVG.");return}if(file.size>1000000){setMessage("A logo deve ter no máximo 1 MB.");return}const reader=new FileReader();reader.onload=()=>setSettings((s)=>s?{...s,logoData:String(reader.result)}:s);reader.readAsDataURL(file)}
 const configured=useMemo(()=>settings?keys.filter(k=>settings[k]).length:0,[settings]);
 const systemStatus=useMemo(()=>({operational:17,configured,missing:Math.max(0,keys.length-configured)}),[configured]);
 const currentUser=users.find(u=>u.id===selected)||null;
 if(loading)return <section className="page"><div className="panel" style={{padding:20}}>Carregando centro de comando...</div></section>;
 if(!settings)return <section className="page"><div className="page-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Centro de comando</h1></div></div><div className="panel" style={{padding:20}}><strong>Não autenticado.</strong><p style={{marginTop:6,color:"var(--muted)"}}>{message}</p><button className="secondary" style={{marginTop:12}} onClick={load}>Tentar novamente</button></div></section>;
 return <section className="page settings-page">
  <div className="page-heading settings-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Centro de comando</h1><p>Configuração central do MB Óptica Gestão Inteligente.</p></div><div className="settings-status"><b>● Sistema operacional</b><span>{systemStatus.operational} módulos operacionais · {systemStatus.missing} parâmetros cadastrais pendentes</span></div></div>
  {message&&<div className="panel settings-message">{message}</div>}
  <div className="settings-actions">{actions.map(([title,href,sub])=><Link key={href} href={href} className="settings-action"><b>+ {title}</b><span>{sub}</span></Link>)}</div>
  <div className="settings-tabs">{[["GERAL","Geral"],["USUARIOS","Usuários e perfis"],["OPERACAO","Operação"],["FISCAL","Fiscal"],["FINANCEIRO","Financeiro"],["SEGURANCA","Segurança"],["SISTEMA","Sistema"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==="GERAL"&&<><div className="settings-grid">
    <div className="panel"><div className="panel-heading"><div><h2>Identidade da óptica</h2><p>Dados usados em documentos, impressões e comunicações.</p></div><button className="primary" disabled={busy} onClick={save}>Salvar alterações</button></div><div className="logo-settings"><div className="logo-preview">{settings.logoData?<img src={settings.logoData} alt="Logo da óptica"/>:<span>MB</span>}</div><div><b>Logo da óptica</b><p>PNG, JPG, WEBP ou SVG · até 1 MB. Será usada na identidade do sistema e poderá ser aproveitada em documentos.</p><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>handleLogo(e.target.files?.[0]||null)}/>{settings.logoData&&<button className="secondary" style={{marginTop:8}} onClick={()=>setSettings({...settings,logoData:null})}>Remover logo</button>}</div></div><div className="settings-form">{keys.map(k=><label key={k}>{labels[k]}<input placeholder={labels[k]} value={settings[k]??""} onChange={e=>setSettings({...settings,[k]:e.target.value||null})}/></label>)}</div></div>
    <div className="panel"><div className="panel-heading"><div><h2>Mapa do sistema</h2><p>Áreas sob controle deste centro.</p></div></div><div className="settings-list"><div><b>Operação</b><span>Clientes, agenda, vendas, pedidos e laboratório.</span></div><div><b>Patrimônio</b><span>Produtos, estoque, fornecedores e custos.</span></div><div><b>Gestão</b><span>Financeiro, relatórios, auditoria e indicadores.</span></div><div><b>Fiscal</b><span>Preparado para configuração fiscal e documentos eletrônicos.</span></div></div></div>
  </div></>}
  {tab==="USUARIOS"&&<div className="settings-grid">
   <div className="panel"><div className="panel-heading"><div><h2>Usuários e perfis</h2><p>Crie usuários e controle o que cada pessoa pode acessar.</p></div></div><div className="settings-form user-form"><label>Nome<input value={newUser.name} onChange={e=>setNewUser({...newUser,name:e.target.value})}/></label><label>E-mail<input value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/></label><label>Senha<input type="password" placeholder="mín. 8 caracteres" value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/></label><label>Perfil<select value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className="primary" disabled={busy} onClick={createUser}>Criar usuário</button></div><div className="table"><div className="row header"><span>Nome</span><span>E-mail</span><span>Perfil</span><span>Status</span><span>Ações</span></div>{users.map(u=><div className="row" key={u.id}><strong>{u.name}</strong><span>{u.email}</span><span>{roles[u.role]??u.role}</span><span>{u.active?"Ativo":"Inativo"}</span><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="secondary" onClick={()=>setSelected(selected===u.id?null:u.id)}>{selected===u.id?"Fechar":"Permissões"}</button><button className="secondary" onClick={()=>{setPasswordUser(passwordUser?.id===u.id?null:u);setNewPassword("");setShowPassword(false)}}>{passwordUser?.id===u.id?"Fechar senha":"Alterar senha"}</button></div></div>)}</div></div>
   <div className="panel permission-panel"><div className="panel-heading"><div><h2>{currentUser?"Permissões de "+currentUser.name:"Permissões individuais"}</h2><p>{currentUser?"O perfil define o acesso-base; aqui você pode criar restrições individuais por módulo.":"Selecione um usuário na lista para configurar."}</p></div></div>{passwordUser&&<div className="panel" style={{marginBottom:16,padding:16}}><div className="panel-heading"><div><h3 style={{margin:0}}>Alterar senha</h3><p style={{marginTop:4}}>Nova senha para {passwordUser.name}. Mínimo de 8 caracteres.</p></div></div><div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap"}}><label style={{flex:"1 1 280px"}}>Nova senha<input type={showPassword?"text":"password"} minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="Mínimo de 8 caracteres"/></label><button className="secondary" type="button" onClick={()=>setShowPassword(!showPassword)}>{showPassword?"Ocultar":"Mostrar"}</button><button className="primary" type="button" disabled={busy||newPassword.length<8} onClick={changePassword}>Salvar nova senha</button></div></div>{currentUser?<div><div className="permission-meta"><b>{roles[currentUser.role]||currentUser.role}</b><span>Permissões individuais prevalecem quando houver uma restrição explícita.</span><button className="secondary" disabled={busy} onClick={()=>resetPermissions(currentUser)}>Restaurar padrão do perfil</button></div>{permissionGroups.map(g=><div className="permission-group" key={g.title}><h3>{g.title}</h3>{g.items.map(([key,label])=><label key={key} className="permission-item"><span><b>{label}</b><small>{hasAccess(currentUser,key)?"Acesso permitido":"Acesso bloqueado"}</small></span><input type="checkbox" checked={hasAccess(currentUser,key)} disabled={busy||currentUser.role==="ADMIN"} onChange={e=>setPermission(currentUser,key,e.target.checked)}/></label>)}</div>)}{currentUser.role==="ADMIN"&&<p className="permission-note">Administradores mantêm acesso integral ao sistema.</p>}</div>:<div style={{padding:"20px",color:"var(--muted)"}}>Clique em <b>Permissões</b> ao lado de um usuário.</div>}</div>
  </div>}
  {tab==="OPERACAO"&&<SettingsPanel title="Operação" text="Parâmetros para o funcionamento diário da óptica." links={[["Clientes","/clientes"],["Agenda","/agenda"],["Vendas","/vendas"],["Pedidos","/pedidos"],["Laboratório","/laboratorio"],["Produtos","/produtos"],["Estoque","/estoque"],["Fornecedores","/fornecedores"]]}/>}
  {tab==="FISCAL"&&<SettingsPanel title="Centro fiscal" text="Área reservada para parametrização fiscal e acompanhamento de documentos." links={[["Vendas e documentos","/vendas"],["Relatórios","/relatorios"],["Configurações gerais","/configuracoes"]]}/>}
  {tab==="FINANCEIRO"&&<SettingsPanel title="Centro financeiro" text="Parâmetros e atalhos para caixa, contas, recebimentos e pagamentos." links={[["Financeiro","/financeiro"],["Vendas","/vendas"],["Relatórios","/relatorios"]]}/>}
  {tab==="SEGURANCA"&&<SettingsPanel title="Segurança e governança" text="Controles de acesso, rastreabilidade e auditoria das operações." links={[["Usuários e perfis","/configuracoes"],["Auditoria","/relatorios"],["Migração","/migracao"]]}/>}
  {tab==="SISTEMA"&&<SettingsPanel title="Sistema e manutenção" text="Ferramentas administrativas para manutenção, integridade e evolução do MB Óptica." links={[["Relatórios","/relatorios"],["Migração","/migracao"],["Saúde do sistema","/api/health"]]}/>}
 </section>
}
function SettingsPanel({title,text,links}:{title:string;text:string;links:string[][]}){return <div className="settings-grid"><div className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>{text}</p></div></div><div className="settings-link-grid">{links.map(([label,href])=><Link key={href+label} href={href}>{label}</Link>)}</div></div><div className="panel"><div className="panel-heading"><div><h2>Governança</h2><p>Princípios do centro de comando.</p></div></div><div className="settings-list"><div><b>Rastreabilidade</b><span>Operações relevantes devem permanecer auditáveis.</span></div><div><b>Permissões</b><span>Ações administrativas respeitam o perfil do usuário.</span></div><div><b>Integridade</b><span>Dados críticos devem ser validados antes de alterações.</span></div></div></div></div>}
