"use client";
import {useEffect,useState} from "react";
type Customer={id:string;name:string;cpfCnpj?:string|null};
type Rx=any;
const empty={customerId:"",professional:"",validUntil:"",odSphere:"",odCylinder:"",odAxis:"",odAdd:"",odPrism:"",odDnp:"",odHeight:"",oeSphere:"",oeCylinder:"",oeAxis:"",oeAdd:"",oePrism:"",oeDnp:"",oeHeight:"",pdTotal:"",notes:""};
const nums=["odSphere","odCylinder","odAxis","odAdd","odPrism","odDnp","odHeight","oeSphere","oeCylinder","oeAxis","oeAdd","oePrism","oeDnp","oeHeight","pdTotal"];
export default function Receitas(){
 const [rows,setRows]=useState<Rx[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[form,setForm]=useState(empty),[open,setOpen]=useState(false),[search,setSearch]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setMessage("");try{const [r,c]=await Promise.all([fetch("/api/prescriptions"),fetch("/api/customers")]);const rd=await r.json(),cd=await c.json();if(!r.ok)throw new Error(rd.error||"Não foi possível carregar as receitas.");if(!c.ok)throw new Error(cd.error||"Não foi possível carregar os clientes.");setRows(rd);setCustomers(cd)}catch(e){setMessage(e instanceof Error?e.message:"Erro ao carregar o módulo.");}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const r=await fetch("/api/prescriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setMessage(d.error||"Não foi possível registrar a receita.");return}setMessage("Receita registrada com sucesso.");setForm(empty);setOpen(false);load()};
 const filtered=rows.filter(r=>{const c=customers.find(x=>x.id===r.customerId);return ((c?.name||"")+" "+(c?.cpfCnpj||"")+" "+(r.professional||"")).toLowerCase().includes(search.toLowerCase())});
 return <section className="page"><div className="page-heading"><div><span className="eyebrow">MB ÓPTICA</span><h1>Receitas ópticas</h1><p>Cadastro e histórico de receitas vinculadas aos clientes.</p></div><button className="primary" onClick={()=>setOpen(true)}>+ Nova receita</button></div>
 {message&&<div className="panel" style={{padding:12,marginBottom:12}}>{message}</div>}
 <div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente ou profissional..."/><button className="secondary" onClick={load}>Atualizar</button></div>
 {open&&<div className="panel" style={{padding:20,marginBottom:12}}><div className="panel-heading" style={{padding:0,marginBottom:15}}><h2>Nova receita</h2><button className="secondary" onClick={()=>setOpen(false)}>Fechar</button></div><form onSubmit={save} style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:8}}><select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">Selecione o cliente</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}{c.cpfCnpj?" — "+c.cpfCnpj:""}</option>)}</select><input placeholder="Profissional" value={form.professional} onChange={e=>setForm({...form,professional:e.target.value})}/><input type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/>{nums.map(k=><input key={k} placeholder={k} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<input style={{gridColumn:"1 / -1"}} placeholder="Observações" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="primary" type="submit">Registrar receita</button></form></div>}
 <div className="panel"><div className="table"><div className="row header"><span>Cliente</span><span>Data</span><span>Profissional</span><span>OD</span><span>OE</span><span>Validade</span></div>{loading?<div style={{padding:20}}>Carregando...</div>:filtered.map(r=>{const c=customers.find(x=>x.id===r.customerId);return <div className="row" key={r.id}><strong>{c?.name||"Cliente"}</strong><span>{r.date?new Date(r.date).toLocaleDateString("pt-BR"):"—"}</span><span>{r.professional||"—"}</span><span>{r.odSphere??"—"} / {r.odCylinder??"—"} / {r.odAxis??"—"}</span><span>{r.oeSphere??"—"} / {r.oeCylinder??"—"} / {r.oeAxis??"—"}</span><span>{r.validUntil?new Date(r.validUntil).toLocaleDateString("pt-BR"):"—"}</span></div>})}</div></div></section>
}