"use client";
import {useEffect,useState} from "react";
const empty={code:"",barcode:"",description:"",unit:"UN",cost:"0",salePrice:"0",minimumStock:"0",categoryId:"",supplierId:"",ncm:"",cest:"",cfop:"",origin:"0",taxCode:""};
export default function Produtos(){
 const [rows,setRows]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[selected,setSelected]=useState<any>(null),[open,setOpen]=useState(false),[search,setSearch]=useState(""),[msg,setMsg]=useState("");
 const load=async()=>{const [p,c,s]=await Promise.all([fetch("/api/products").then(r=>r.json()),fetch("/api/categories").then(r=>r.json()),fetch("/api/suppliers").then(r=>r.json())]);setRows(Array.isArray(p)?p:[]);setCats(Array.isArray(c)?c:[]);setSuppliers(Array.isArray(s)?s:[])};
 useEffect(()=>{load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch(selected?"/api/products/"+selected.id:"/api/products",{method:selected?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,cost:Number(form.cost),salePrice:Number(form.salePrice),minimumStock:Number(form.minimumStock),categoryId:form.categoryId||null,supplierId:form.supplierId||null})});const d=await r.json();if(!r.ok){setMsg(d.error||"Erro ao salvar");return}setOpen(false);setSelected(null);setForm(empty);setMsg("");await load()};
 const edit=(p:any)=>{setSelected(p);setForm({...empty,...p,cost:String(p.cost),salePrice:String(p.salePrice),minimumStock:String(p.minimumStock),categoryId:p.categoryId||"",supplierId:p.supplierId||""});setOpen(true)};
 const filtered=rows.filter(p=>(p.code+" "+p.barcode+" "+p.description).toLowerCase().includes(search.toLowerCase()));
 return <section className="page"><div className="page-heading"><div><span className="eyebrow">CATÁLOGO</span><h1>Produtos</h1><p>Código, barras, categoria, fornecedor, preços, estoque atual, estoque mínimo e dados fiscais.</p></div><button className="primary" onClick={()=>{setSelected(null);setForm(empty);setOpen(true)}}>+ Novo produto</button></div>{msg&&<div className="panel" style={{padding:12,color:"#a33"}}>{msg}</div>}<div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar código, código de barras ou descrição..."/></div>
 <div className="panel"><div className="table"><div className="row header"><span>Código</span><span>Produto</span><span>Categoria</span><span>Fornecedor</span><span>Preço</span><span>Estoque</span><span></span></div>{filtered.map(p=><div className="row" key={p.id}><strong>{p.code}</strong><span>{p.description}</span><span>{p.category?.name||"—"}</span><span>{p.supplier?.name||"—"}</span><span>R$ {Number(p.salePrice).toFixed(2)}</span><span style={{fontWeight:600,color:p.lowStock?"#a33":"inherit"}}>{Number(p.stock||0).toFixed(3)} {p.unit} {p.lowStock?"· baixo":""}</span><button className="link-button" onClick={()=>edit(p)}>Editar</button></div>)}</div></div>
 {open&&<div className="panel" style={{padding:20}}><div className="panel-heading" style={{padding:0,marginBottom:15}}><h2>{selected?"Editar produto":"Novo produto"}</h2><button className="secondary" onClick={()=>setOpen(false)}>Fechar</button></div><form onSubmit={save} style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>
 <input placeholder="Código" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input placeholder="Código de barras" value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/><input placeholder="Descrição" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Unidade" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><input type="number" step="0.01" placeholder="Custo" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})}/><input type="number" step="0.01" placeholder="Preço" value={form.salePrice} onChange={e=>setForm({...form,salePrice:e.target.value})}/><input type="number" step="0.001" placeholder="Estoque mínimo" value={form.minimumStock} onChange={e=>setForm({...form,minimumStock:e.target.value})}/><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Categoria</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Fornecedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input placeholder="NCM" value={form.ncm} onChange={e=>setForm({...form,ncm:e.target.value})}/><input placeholder="CEST" value={form.cest} onChange={e=>setForm({...form,cest:e.target.value})}/><input placeholder="CFOP" value={form.cfop} onChange={e=>setForm({...form,cfop:e.target.value})}/><input placeholder="Origem fiscal" value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}/><input placeholder="Código tributário" value={form.taxCode} onChange={e=>setForm({...form,taxCode:e.target.value})}/><button className="primary" type="submit">Salvar produto</button></form></div>}</section>
}
