"use client";
import {useEffect,useState} from "react";
type Product={id:string;code:string;description:string;unit:string;cost:number;stock:number;minimumStock:number;lowStock:boolean};
export default function Estoque(){
 const [rows,setRows]=useState<Product[]>([]),[products,setProducts]=useState<any[]>([]),[mode,setMode]=useState<"entry"|"exit"|null>(null),[form,setForm]=useState({productId:"",quantity:"",cost:"",code:"",expiresAt:"",reason:""}),[msg,setMsg]=useState("");
 const load=async()=>{const [s,p]=await Promise.all([fetch("/api/stock"),fetch("/api/products")]);const sd=await s.json(),pd=await p.json();if(s.ok)setRows(sd);if(p.ok)setProducts(pd);else setMsg(pd.error||"Erro ao carregar produtos.")};
 useEffect(()=>{load()},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setMsg("");const r=await fetch("/api/stock/"+mode,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,quantity:Number(form.quantity),cost:form.cost===""?undefined:Number(form.cost)})});const d=await r.json();if(!r.ok){setMsg(d.error||"Não foi possível concluir a operação.");return}setMsg(mode==="entry"?"Entrada registrada.":"Saída registrada.");setMode(null);setForm({productId:"",quantity:"",cost:"",code:"",expiresAt:"",reason:""});await load()};
 return <section className="page"><div className="page-heading"><div><span className="eyebrow">MB ÓPTICA</span><h1>Estoque</h1><p>Saldo por produto, estoque mínimo e movimentações por lote.</p></div><div style={{display:"flex",gap:8}}><button className="primary" onClick={()=>setMode("entry")}>+ Entrada</button><button className="secondary" onClick={()=>setMode("exit")}>− Saída</button></div></div>
 {msg&&<div className="panel" style={{padding:12}}>{msg}</div>}
 <div className="panel"><div className="table"><div className="row header"><span>Código</span><span>Produto</span><span>Estoque</span><span>Mínimo</span><span>Status</span></div>{rows.map(p=><div className="row" key={p.id}><strong>{p.code}</strong><span>{p.description}</span><span>{Number(p.stock).toFixed(3)} {p.unit}</span><span>{Number(p.minimumStock).toFixed(3)}</span><span style={{color:p.lowStock?"#a33":"inherit"}}>{p.lowStock?"ESTOQUE BAIXO":"OK"}</span></div>)}</div></div>
 {mode&&<div className="panel" style={{padding:20,marginTop:12}}><div className="panel-heading" style={{padding:0,marginBottom:15}}><h2>{mode==="entry"?"Entrada de estoque":"Saída de estoque"}</h2><button className="secondary" onClick={()=>setMode(null)}>Fechar</button></div><form onSubmit={submit} style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}><select required value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}><option value="">Selecione o produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.code} — {p.description}</option>)}</select><input required type="number" min="0.001" step="0.001" placeholder="Quantidade" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/>{mode==="entry"&&<><input type="number" min="0" step="0.01" placeholder="Custo do lote (opcional)" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})}/><input placeholder="Código do lote" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input type="date" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></>}<input placeholder="Motivo / observação" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button className="primary" type="submit">{mode==="entry"?"Registrar entrada":"Registrar saída"}</button></form></div>}</section>
}