"use client";
import {useEffect,useState} from "react";
const empty={name:"",document:"",phone:"",email:"",notes:""};
export default function Fornecedores(){
 const [rows,setRows]=useState<any[]>([]),[form,setForm]=useState(empty),[selected,setSelected]=useState<any>(null),[open,setOpen]=useState(false),[msg,setMsg]=useState("");
 const load=async()=>{const r=await fetch("/api/suppliers");const d=await r.json();if(r.ok)setRows(d);else setMsg(d.error||"Erro ao carregar fornecedores.")};useEffect(()=>{load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch(selected?"/api/suppliers/"+selected.id:"/api/suppliers",{method:selected?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setMsg(d.error||"Erro ao salvar");return}setOpen(false);setSelected(null);setForm(empty);await load()};
 const edit=async(s:any)=>{const d=await fetch("/api/suppliers/"+s.id).then(r=>r.json());setSelected(d);setForm({name:d.name,document:d.document||"",phone:d.phone||"",email:d.email||"",notes:d.notes||""});setOpen(true)};
 return <section className="page"><div className="page-heading"><div><span className="eyebrow">CADASTRO</span><h1>Fornecedores</h1><p>Cadastro, contatos, produtos vinculados e contas a pagar.</p></div><button className="primary" onClick={()=>{setSelected(null);setForm(empty);setOpen(true)}}>+ Novo fornecedor</button></div>{msg&&<div className="panel" style={{padding:12,color:"#a33"}}>{msg}</div>}<div className="panel"><div className="table"><div className="row header"><span>Fornecedor</span><span>Documento</span><span>Telefone</span><span>Produtos</span><span>Contas</span><span></span></div>{rows.map(s=><div className="row" key={s.id}><strong>{s.name}</strong><span>{s.document||"—"}</span><span>{s.phone||"—"}</span><span>{s._count?.products??0}</span><span>{s._count?.accounts??0}</span><button className="link-button" onClick={()=>edit(s)}>Abrir</button></div>)}</div></div>
 {open&&<div className="panel" style={{padding:20}}><div className="panel-heading" style={{padding:0,marginBottom:15}}><h2>{selected?"Editar fornecedor":"Novo fornecedor"}</h2><button className="secondary" onClick={()=>setOpen(false)}>Fechar</button></div><form onSubmit={save} style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:10}}>{Object.entries(form).map(([k,v])=><input key={k} placeholder={k} value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<button className="primary" type="submit">Salvar fornecedor</button></form>{selected&&<><h3 style={{fontSize:12,marginTop:25}}>Produtos vinculados</h3>{selected.products?.map((p:any)=><div key={p.id} style={{fontSize:10,padding:"8px 0",borderTop:"1px solid var(--line)"}}>{p.code} — {p.description} — R$ {Number(p.salePrice).toFixed(2)}</div>)}<h3 style={{fontSize:12,marginTop:25}}>Contas a pagar</h3>{selected.accounts?.filter((a:any)=>a.status!=="PAGO"&&a.status!=="CANCELADO").map((a:any)=><div key={a.id} style={{fontSize:10,padding:"8px 0",borderTop:"1px solid var(--line)"}}>{a.description} — venc. {new Date(a.dueDate).toLocaleDateString("pt-BR")} — R$ {Number(a.amount-a.paidAmount).toFixed(2)}</div>)}</>}</div>}</section>
}
