"use client";
import {useEffect,useState} from "react";
const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const tabs=["VISÃO","SAÚDE DO FATURAMENTO","VENDAS","ESTOQUE","PEDIDOS","FINANCEIRO","CLIENTES","ORÇAMENTOS","PRESCRIÇÕES","AGENDA","FISCAL","AUDITORIA","INCONSISTÊNCIAS"];
const Card=({t,v,d}:{t:string;v:any;d?:string})=><div className="report-card"><span>{t}</span><strong>{v}</strong>{d&&<small>{d}</small>}</div>;
export default function Relatorios(){
 const[d,setD]=useState<any>(null);const[legacy,setLegacy]=useState<any>(null);const[tab,setTab]=useState("VISÃO");const[q,setQ]=useState("");
 useEffect(()=>{fetch("/api/migration/financial-summary",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setLegacy).catch(()=>{})},[]);
 useEffect(()=>{fetch("/api/relatorios",{cache:"no-store"}).then(r=>r.json()).then(setD)},[]);
 if(!d)return <section className="page"><div className="panel"><div className="panel-heading"><div><h2>Gerando relatórios...</h2><p>Consolidando todos os módulos.</p></div></div></div></section>;
 const s=d.summary,inc=d.inconsistencies||[];
 const download=()=>{const b=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="mb-optica-relatorios.json";a.click();URL.revokeObjectURL(u)};
 const row=(a:any,b:any,c:any="",e:any="")=><div className="report-row"><span>{a}</span><span>{b}</span><span>{c}</span><strong>{e}</strong></div>;
 return <section className="page reports-page">
 <div className="page-heading"><div><span className="eyebrow">GESTÃO INTELIGENTE</span><h1>Relatórios</h1><p>Informações completas do sistema, desempenho, rastreabilidade e integridade.</p></div><div className="report-actions"><button className="secondary" onClick={()=>window.print()}>🖨 Imprimir</button><button className="primary" onClick={download}>⇩ Exportar</button></div></div>
 {inc.length?<div className="report-alert"><div><b>⚠ {inc.length} inconsistência(s)</b><span>Existem registros que precisam de conferência.</span></div><button className="secondary" onClick={()=>setTab("INCONSISTÊNCIAS")}>Ver alertas</button></div>:<div className="report-ok">✓ Nenhuma inconsistência automática encontrada.</div>}
 <div className="report-tabs">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {tab==="VISÃO"&&<><div className="report-kpis"><Card t="Vendas" v={s.sales}/><Card t="Faturamento" v={money(s.saleTotal)}/><Card t="Margem bruta" v={money(s.grossMargin)}/><Card t="A receber" v={money(s.receivable)}/><Card t="A pagar" v={money(s.payable)}/><Card t="Estoque baixo" v={s.lowStock}/><Card t="Pedidos" v={s.orders}/><Card t="Alertas" v={s.inconsistencies}/></div><div className="report-grid-2"><div className="panel"><div className="panel-heading"><div><h2>Evolução mensal</h2><p>Vendas e recebimentos dos últimos 12 meses.</p></div></div><div className="report-table"><div className="report-row head"><span>Mês</span><span>Vendas</span><span>Faturamento</span><span>Recebido</span></div>{d.sales.monthly.map((x:any)=>row(x.month,x.sales,"",money(x.total)))}</div></div><div className="panel"><div className="panel-heading"><div><h2>Resumo operacional</h2></div></div><div className="report-metrics"><div><b>{s.activeCustomers}</b><span>clientes ativos</span></div><div><b>{s.zeroStock}</b><span>produtos zerados</span></div><div><b>{d.quotes.open}</b><span>orçamentos abertos</span></div><div><b>{d.appointments.today}</b><span>agendamentos hoje</span></div><div><b>{d.fiscal.rejected}</b><span>fiscais rejeitados</span></div><div><b>{s.auditEvents}</b><span>eventos auditados</span></div></div></div></div></>}
 {tab==="SAÚDE DO FATURAMENTO"&&(()=>{
   const faturamento=n(s.saleTotal), recebido=n(s.received), aReceber=n(s.receivable), aPagar=n(s.payable), custo=n(s.saleCost), margem=n(s.grossMargin);
   const taxaReceb=faturamento>0?recebido/faturamento:0;
   const margemPct=faturamento>0?margem/faturamento:0;
   const pontos:any[]=[];
   const add=(nivel:string,item:string,evidencia:string,acao:string)=>pontos.push({nivel,item,evidencia,acao});
   if(faturamento<=0)add("ATENÇÃO","Não há faturamento operacional no MB Óptica","O histórico operacional atual do MB ainda não apresenta vendas faturadas.","Acompanhar as vendas novas diariamente e manter o histórico BeepStart separado até a transição estar consolidada.");
   if(aReceber>0&&faturamento>0&&aReceber/faturamento>=0.25)add("ATENÇÃO","Saldo a receber elevado em relação ao faturamento","O saldo a receber representa "+(aReceber/faturamento*100).toFixed(1)+"% do faturamento operacional acumulado.","Priorizar cobrança dos títulos vencidos e acompanhar os próximos vencimentos.");
   if(aPagar>0&&faturamento>0&&aPagar/faturamento>=0.25)add("ATENÇÃO","Compromissos a pagar relevantes","O saldo a pagar representa "+(aPagar/faturamento*100).toFixed(1)+"% do faturamento operacional acumulado.","Revisar vencimentos, fluxo de caixa e programação de pagamentos.");
   if(faturamento>0&&taxaReceb<0.7)add("ATENÇÃO","Conversão de faturamento em recebimento","Apenas "+(taxaReceb*100).toFixed(1)+"% do faturamento operacional acumulado aparece como recebido nos dados atuais.","Separar claramente vendas faturadas, recebimentos e contas a receber para acompanhar a conversão de caixa.");
   if(faturamento>0&&margemPct<0.25)add("ATENÇÃO","Margem bruta merece acompanhamento","A margem bruta calculada está em "+(margemPct*100).toFixed(1)+"% do faturamento.","Revisar custos dos produtos, descontos e preços de venda.");
   if(s.lowStock>0)add("ATENÇÃO","Estoque abaixo do mínimo","Há "+s.lowStock+" produto(s) abaixo do estoque mínimo.","Revisar reposição dos itens com maior giro antes de perder vendas.");
   if(s.zeroStock>0)add("ATENÇÃO","Produtos sem estoque","Há "+s.zeroStock+" produto(s) zerado(s).","Verificar se algum item de venda recorrente precisa de reposição.");
   if(d.quotes.expired>0)add("ATENÇÃO","Orçamentos vencidos","Há "+d.quotes.expired+" orçamento(s) aberto(s) e vencido(s).","Entrar em contato com os clientes e atualizar o status dos orçamentos.");
   if(d.fiscal.rejected>0)add("ATENÇÃO","Documentos fiscais rejeitados","Há "+d.fiscal.rejected+" documento(s) fiscal(is) rejeitado(s).","Corrigir as rejeições antes de considerar o faturamento fiscal plenamente conciliado.");
   if(d.inconsistencies>0)add("ATENÇÃO","Inconsistências de dados","O sistema encontrou "+d.inconsistencies+" alerta(s) automático(s).","Abrir a Central de integridade e corrigir os registros antes de fechar análises.");
   if(legacy?.ok){
     if(legacy.receivable>0)add("ACOMPANHAR","Contas a receber do legado BeepStart","O histórico BeepStart possui "+money(legacy.receivable)+" ainda em aberto.","Acompanhar essas contas no cadastro dos clientes e migrá-las seletivamente, sem duplicar vendas.");
     if(legacy.billing>0)add("ACOMPANHAR","Faturamento histórico ainda está no BeepStart","O BeepStart registra "+money(legacy.billing)+" de faturamento em 2026, separado do faturamento operacional do MB.","Usar o bloco histórico como referência até a transição financeira ser concluída.");
   }
   if(!pontos.length)add("ACOMPANHAR","Nenhum ponto crítico identificado automaticamente","Os indicadores disponíveis não acionaram os critérios de atenção configurados.","Continuar o acompanhamento periódico e revisar os indicadores ao longo do mês.");
   return <div className="panel full">
    <div className="panel-heading"><div><span className="eyebrow">ANÁLISE AUTOMÁTICA</span><h2>Saúde do faturamento</h2><p>Relatório interpretativo com evidências e pontos que merecem acompanhamento.</p></div><div className="report-actions"><button className="secondary" onClick={()=>window.print()}>🖨 Imprimir relatório</button></div></div>
    <div className="report-kpis compact"><Card t="Faturamento MB" v={money(faturamento)} d="vendas operacionais"/><Card t="Recebido MB" v={money(recebido)} d={faturamento?((taxaReceb*100).toFixed(1)+"% do faturamento"):"sem base"}/><Card t="A receber MB" v={money(aReceber)}/><Card t="A pagar MB" v={money(aPagar)}/><Card t="Margem bruta" v={money(margem)} d={faturamento?(margemPct*100).toFixed(1)+"% do faturamento":"sem base"}/></div>
    <div className="panel" style={{marginTop:16}}><div className="panel-heading"><div><h2>Pontos que merecem atenção</h2><p>O sistema mostra o indicador, a evidência encontrada e uma abordagem sugerida.</p></div><span className="alert-badge">{pontos.length} ponto(s)</span></div>
      <div className="report-table"><div className="report-row head"><span>Nível</span><span>Item</span><span>Evidência</span><span>Abordagem sugerida</span></div>{pontos.map((p,i)=><div className="report-row" key={i}><strong>{p.nivel}</strong><span><b>{p.item}</b></span><span>{p.evidencia}</span><span>{p.acao}</span></div>)}</div>
    </div>
    {legacy?.ok&&<div className="report-grid-2" style={{marginTop:16}}><div className="panel"><div className="panel-heading"><div><h2>Histórico BeepStart</h2><p>Base histórica separada do operacional atual.</p></div></div><div className="report-metrics"><div><b>{money(legacy.billing)}</b><span>faturamento 2026</span></div><div><b>{money(legacy.received)}</b><span>recebido 2026</span></div><div><b>{money(legacy.receivable)}</b><span>a receber</span></div><div><b>{legacy.salesCount}</b><span>vendas históricas</span></div></div></div><div className="panel"><div className="panel-heading"><div><h2>Leitura gerencial</h2><p>Como interpretar o relatório.</p></div></div><p style={{lineHeight:1.7,fontSize:13}}>O relatório não classifica a empresa por uma nota única. Ele identifica relações entre faturamento, recebimento, contas a receber, contas a pagar, margem, estoque, orçamentos e integridade dos dados. Cada alerta deve ser analisado junto com sua evidência antes de qualquer decisão.</p></div></div>}
   </div>;
 })()}
 {tab==="VENDAS"&&<div className="report-grid-2"><div className="panel"><div className="panel-heading"><div><h2>Vendas por vendedor</h2></div></div><div className="report-table">{d.sales.bySeller.map((x:any)=>row(x.name,"","",money(x.total)))}</div></div><div className="panel"><div className="panel-heading"><div><h2>Meios de pagamento</h2></div></div><div className="report-table">{d.sales.paymentMethods.map((x:any)=>row(x.name,"","",money(x.value)))}</div></div><div className="panel full"><div className="panel-heading"><div><h2>Itens com maior faturamento</h2></div></div><div className="report-table">{d.sales.topItems.map((x:any,i:number)=>row("#"+(i+1)+" · "+x.description,"","",money(x.total)))}</div></div></div>}
 {tab==="ESTOQUE"&&<div className="report-grid-2"><div className="panel full"><div className="panel-heading"><div><h2>Posição do estoque</h2><p>Filtre por código ou descrição.</p></div><input className="report-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar produto..." /></div><div className="report-table"><div className="report-row head"><span>Produto</span><span>Qtd.</span><span>Mín.</span><span>Status</span></div>{d.stock.items.filter((x:any)=>!q||x.description.toLowerCase().includes(q.toLowerCase())||x.code.toLowerCase().includes(q.toLowerCase())).slice(0,150).map((x:any)=>row(x.code+" · "+x.description,x.quantity,x.minimum,x.quantity<=0?"ZERADO":x.quantity<=x.minimum?"BAIXO":"OK"))}</div></div></div>}
 {tab==="PEDIDOS"&&<div className="panel"><div className="panel-heading"><div><h2>Pedidos e laboratório</h2><p>Fluxo por status e pedidos recentes.</p></div></div><div className="report-status-grid">{Object.entries(d.orders.byStatus).map(([k,v]:any)=><div key={k}><span>{k.replaceAll("_"," ")}</span><b>{v}</b></div>)}</div><div className="report-table">{d.orders.recent.slice(0,100).map((x:any)=>row("#"+x.number,x.customer,x.status,x.laboratory||"—"))}</div></div>}
 {tab==="FINANCEIRO"&&<div className="report-grid-2"><div className="panel"><div className="report-kpis compact"><Card t="A receber" v={money(s.receivable)}/><Card t="A pagar" v={money(s.payable)}/><Card t="Recebido" v={money(s.received)}/><Card t="Pago" v={money(s.payablePaid)}/></div></div><div className="panel"><div className="report-kpis compact"><Card t="Saldo de caixa" v={money(s.cashBalance)}/><Card t="Caixas abertos" v={s.openCash}/><Card t="Sessões" v={d.finance.cashSessions.length}/></div></div><div className="panel full"><div className="panel-heading"><div><h2>Liquidações recentes</h2></div></div><div className="report-table">{d.finance.settlements.slice(0,100).map((x:any)=>row(new Date(x.paidAt).toLocaleDateString("pt-BR"),x.account.description,x.account.type,money(x.amount)))}</div></div></div>}
 {tab==="CLIENTES"&&<div className="panel"><div className="report-kpis compact"><Card t="Total" v={s.customers}/><Card t="Ativos" v={s.activeCustomers}/><Card t="Novos 30 dias" v={d.customers.new30}/><Card t="Com telefone/WhatsApp" v={d.customers.withPhone}/><Card t="Sem CPF/CNPJ" v={d.customers.withoutDocument}/></div></div>}
 {tab==="ORÇAMENTOS"&&<div className="panel"><div className="report-kpis compact"><Card t="Total" v={s.quotes}/><Card t="Abertos" v={d.quotes.open}/><Card t="Vencidos" v={d.quotes.expired}/><Card t="Convertidos" v={d.quotes.converted}/></div></div>}
 {tab==="PRESCRIÇÕES"&&<div className="panel"><div className="report-kpis compact"><Card t="Total" v={d.prescriptions.total}/><Card t="Válidas" v={d.prescriptions.valid}/><Card t="Vencidas" v={d.prescriptions.expired}/></div></div>}
 {tab==="AGENDA"&&<div className="panel"><div className="report-kpis compact"><Card t="Total" v={d.appointments.total}/><Card t="Hoje" v={d.appointments.today}/><Card t="Agendados" v={d.appointments.pending}/></div></div>}
 {tab==="FISCAL"&&<div className="panel"><div className="report-kpis compact"><Card t="Total" v={d.fiscal.total}/><Card t="Autorizados" v={d.fiscal.authorized}/><Card t="Pendentes" v={d.fiscal.pending}/><Card t="Rejeitados" v={d.fiscal.rejected}/></div></div>}
 {tab==="AUDITORIA"&&<div className="panel"><div className="panel-heading"><div><h2>Trilha de auditoria</h2><p>Quem fez o quê e quando.</p></div><input className="report-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar..." /></div><div className="report-table">{d.audit.events.filter((x:any)=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())).slice(0,150).map((x:any)=>row(new Date(x.createdAt).toLocaleString("pt-BR"),x.user?.name||"Sistema",x.action,x.entity+(x.entityId?" · "+x.entityId.slice(0,8):"")))}</div></div>}
 {tab==="INCONSISTÊNCIAS"&&<div className="panel"><div className="panel-heading"><div><h2>Central de integridade</h2><p>Verificações automáticas sobre financeiro, vendas, estoque, pedidos, fiscal e cadastros.</p></div><span className={inc.length?"alert-badge":"good-badge"}>{inc.length} alerta(s)</span></div><div className="report-table">{inc.length?inc.map((x:any,i:number)=>row(x.severity,x.type,x.message,x.entity||"—")):<div className="empty-state">✓ Nenhuma inconsistência encontrada.</div>}</div></div>}
 <div className="report-foot">Atualizado em {new Date(d.generatedAt).toLocaleString("pt-BR")} · Os alertas são automáticos e devem ser conferidos antes de decisões operacionais.</div>
 </section>
}