ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'PREMIUM';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'PROPRIETARIO';

ALTER TABLE "Subscription"
  ADD COLUMN "maxUnits" INTEGER,
  ADD COLUMN "maxClients" INTEGER,
  ADD COLUMN "maxProducts" INTEGER,
  ADD COLUMN "maxSales" INTEGER,
  ADD COLUMN "maxOrders" INTEGER,
  ADD COLUMN "trialDays" INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN "graceDays" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN "licenseType" TEXT NOT NULL DEFAULT 'SUBSCRIPTION';
