"use client";
import {useEffect,useMemo,useState} from "react";
import {StatusBadge} from "@/components/StatusBadge";

type Customer={id:string;name:string;cpfCnpj?:string|null;phone?:string|null;email?:string|null};
type Product={id:string;code:string;description:string;salePrice:number|string};
type Order=any;

const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dateBR=(v:any)=>v?new Date(v).toLocaleDateString("pt-BR"):"—";
const labels:any={ORCAMENTO:"Orçamento",APROVADO:"Aprovado",PEDIDO:"Pedido",AGUARDANDO_LABORATORIO:"Aguardando laboratório",EM_PRODUCAO:"Em produção",RECEBIDO:"Recebido",CONFERENCIA:"Conferência",PRONTO:"Pronto",ENTREGUE:"Entregue"};
const next:any={PEDIDO:"AGUARDANDO_LABORATORIO",AGUARDANDO_LABORATORIO:"EM_PRODUCAO",EM_PRODUCAO:"RECEBIDO",RECEBIDO:"CONFERENCIA",CONFERENCIA:"PRONTO",PRONTO:"ENTREGUE"};

const emptyRx:any={professional:"",validUntil:"",odSphere:"",odCylinder:"",odAxis:"",odAdd:"",odPrism:"",odBase:"",odDnp:"",odHeight:"",oeSphere:"",oeCylinder:"",oeAxis:"",oeAdd:"",oePrism:"",oeBase:"",oeDnp:"",oeHeight:"",pdTotal:"",notes:""};
const newItem=()=>({productId:"",description:"",kind:"LENTE",quantity:"1",unitPrice:"0",eye:""});

export default function Atendimento(){
 const [stage,setStage]=useState("RECEITA"),[open,setOpen]=useState(true),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true);
 const [customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[prescriptions,setPrescriptions]=useState<any[]>([]),[orders,setOrders]=useState<Order[]>([]);
 const [customerId,setCustomerId]=useState(""),[query,setQuery]=useState("");
 const [rx,setRx]=useState({...emptyRx}),[rxProfessional,setRxProfessional]=useState("");
 const [quoteRx,setQuoteRx]=useState(""),[quoteItems,setQuoteItems]=useState<any[]>([newItem()]),[quoteDiscount,setQuoteDiscount]=useState("0"),[quoteSurcharge,setQuoteSurcharge]=useState("0"),[quoteEntry,setQuoteEntry]=useState("0"),[quotePayment,setQuotePayment]=useState(""),[quoteNotes,setQuoteNotes]=useState("");
 const [orderRx,setOrderRx]=useState(""),[orderItems,setOrderItems]=useState<any[]>([newItem()]),[laboratory,setLaboratory]=useState(""),[dueDate,setDueDate]=useState(""),[orderNotes,setOrderNotes]=useState("");

 const load=async()=>{setLoading(true);try{const [c,p,r,o]=await Promise.all([fetch("/api/customers"),fetch("/api/products"),fetch("/api/prescriptions"),fetch("/api/orders")]);const [cd,pd,rd,od]=await Promise.all([c.json(),p.json(),r.json(),o.json()]);if(c.ok)setCustomers(cd);if(p.ok)setProducts(pd);if(r.ok)setPrescriptions(rd);if(o.ok)setOrders(od)}catch{setMsg("Erro ao carregar o fluxo.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const customer=customers.find(c=>c.id===customerId);
 const customerRx=useMemo(()=>prescriptions.filter(r=>r.customerId===customerId),[prescriptions,customerId]);
 const matches=(text:string)=>products.filter(p=>(p.code+" "+p.description).toLowerCase().includes(text.toLowerCase())).slice(0,6);
 const qtotal=quoteItems.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.unitPrice||0),0);
 const total=Math.max(0,qtotal-Number(quoteDiscount||0)+Number(quoteSurcharge||0));
 const ototal=orderItems.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.unitPrice||0),0);
 const selectCustomer=(c:Customer)=>{setCustomerId(c.id);setQuery(c.name);setQuoteRx("");setOrderRx("");setMsg("")};
 const saveRx=async()=>{if(!customerId){setMsg("Selecione o cliente.");return}const r=await fetch("/api/prescriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...rx,customerId,professional:rxProfessional})});const d=await r.json();if(!r.ok){setMsg(d.error||"Erro ao salvar receita.");return}setPrescriptions([d,...prescriptions]);setQuoteRx(d.id);setOrderRx(d.id);setRx({...emptyRx});setRxProfessional("");setMsg("Receita salva e vinculada ao fluxo.");setStage("ORCAMENTO");setOpen(true)};
 const saveQuote=async()=>{if(!customerId||!quoteItems.length){setMsg("Selecione o cliente e informe os itens.");return}const r=await fetch("/api/quotes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId,prescriptionId:quoteRx||null,discount:quoteDiscount,surcharge:quoteSurcharge,entryAmount:quoteEntry,paymentMethod:quotePayment||null,notes:quoteNotes||null,items:quoteItems.map(i=>({...i,productId:i.productId||null}))})});const d=await r.json();if(!r.ok){setMsg(d.error||"Erro ao criar orçamento.");return}setMsg("ORC-"+String(d.number).padStart(6,"0")+" criado.");await load();setStage("PEDIDO");setOpen(true)};
 const saveOrder=async()=>{if(!customerId||!laboratory.trim()||!orderItems.length){setMsg("Cliente, laboratório e itens são obrigatórios.");return}const me=await fetch("/api/auth/me").then(r=>r.json()),sellerId=me.user?.id||me.id;const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId,prescriptionId:orderRx||undefined,sellerId,laboratory,dueDate:dueDate||undefined,notes:orderNotes,items:orderItems.map(i=>({productId:i.productId||undefined,description:i.description,kind:i.kind,eye:i.eye||undefined,quantity:Number(i.quantity),unitPrice:Number(i.unitPrice||0)}))})});const d=await r.json();if(!r.ok){setMsg(d.error||"Erro ao criar pedido.");return}setMsg("Pedido #"+d.number+" criado.");await load();setStage("LABORATORIO");setOpen(true)};
 const advance=async(o:Order)=>{const n=next[o.status];if(!n)return;const r=await fetch("/api/orders/"+o.id+"/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:n,message:"Atualização pelo fluxo óptico"})});const d=await r.json();if(!r.ok){setMsg(d.error||d.detail||"Erro ao atualizar.");return}setMsg("Pedido #"+o.number+" → "+labels[n]);load()};
 const updateItem=(setter:any,items:any[],i:number,p:any)=>{const n=[...items];n[i]=p;setter(n)};
 const productField=(items:any,setter:any,i:number)=><label>Produto<input value={items[i].description} placeholder="Pesquisar código ou descrição..." onChange={e=>updateItem(setter,items,i,{...items[i],productId:"",description:e.target.value})}/>{items[i].description&&!items[i].productId&&matches(items[i].description).map(p=><button type="button" key={p.id} className="workflow-suggestion" onClick={()=>updateItem(setter,items,i,{...items[i],productId:p.id,description:p.description,unitPrice:String(p.salePrice)})}>{p.code} — {p.description} · {money(p.salePrice)}</button>)}</label>;

 return <section className="page">
  <div className="page-heading"><div><span className="eyebrow">ÓPTICA</span><h1>Atendimento</h1><p>Receita → orçamento → pedido → laboratório em uma única tela.</p></div><button className="secondary" onClick={load}>↻ Atualizar</button></div>
  {msg&&<div className="panel" style={{padding:12,marginBottom:12}}>{msg}</div>}
  <div className="panel workflow-client"><label>Cliente<input value={query} onChange={e=>{setQuery(e.target.value);setCustomerId("")}} placeholder="Pesquisar por nome ou CPF/CNPJ..." autoComplete="off"/>{query&&!customerId&&customers.filter(c=>(c.name+" "+(c.cpfCnpj||"")).toLowerCase().includes(query.toLowerCase())).slice(0,8).map(c=><button type="button" className="workflow-suggestion" key={c.id} onClick={()=>selectCustomer(c)}>{c.name}{c.cpfCnpj?" — "+c.cpfCnpj:""}</button>)}</label><div className="sales-total-box"><span>Cliente</span><strong>{customer?.name||"Selecione"}</strong></div></div>
  <div className="workflow-tabs">{[["RECEITA","Receita","Cadastro OD/OE"],["ORCAMENTO","Orçamento","Itens e valores"],["PEDIDO","Pedido","Produção e entrega"],["LABORATORIO","Laboratório","Acompanhamento"]].map(x=><button key={x[0]} className={"workflow-tab "+(stage===x[0]?"active":"")} onClick={()=>{setStage(x[0]);setOpen(true)}}><b>{x[1]}</b><span>{x[2]}</span></button>)}</div>

  {stage==="RECEITA"&&<div className="panel workflow-panel"><button className="workflow-section-head" onClick={()=>setOpen(!open)}><span><b>Nova receita</b><small>Preenchimento suspenso como no PDV · OD primeiro, depois OE</small></span><strong>{open?"−":"+"}</strong></button>{open&&<div className="workflow-body sales-form">
   <div className="sales-form-grid"><label>Profissional<input value={rxProfessional} onChange={e=>setRxProfessional(e.target.value)}/></label><label>Validade<input type="date" value={rx.validUntil} onChange={e=>setRx({...rx,validUntil:e.target.value})}/></label><label>DP Total<input value={rx.pdTotal} onChange={e=>setRx({...rx,pdTotal:e.target.value})}/></label><div className="sales-total-box"><span>Cliente</span><strong>{customer?.name||"—"}</strong></div></div>
   <div className="workflow-eyes">{["od","oe"].map(side=><div className="panel workflow-eye" key={side}><h3>{side==="od"?"OD — OLHO DIREITO":"OE — OLHO ESQUERDO"}</h3><div className="sales-form-grid">{["Sphere","Cylinder","Axis","Add","Prism","Base","Dnp","Height"].map(k=>{const key=side+k;const lab:any={Sphere:"ESF",Cylinder:"CIL",Axis:"AX",Add:"ADD",Prism:"PRISMA",Base:"BASE",Dnp:"DNP",Height:"ALTURA"};return <label key={key}>{lab[k]}<input value={rx[key]} onChange={e=>setRx({...rx,[key]:e.target.value})}/></label>})}</div></div>)}</div>
   <label className="sales-wide">Observações<textarea rows={3} value={rx.notes} onChange={e=>setRx({...rx,notes:e.target.value})}/></label><div className="sales-actions"><button className="primary" disabled={!customerId} onClick={saveRx}>Salvar receita e seguir →</button></div>
  </div>}</div>}

  {stage==="ORCAMENTO"&&<div className="panel workflow-panel"><button className="workflow-section-head" onClick={()=>setOpen(!open)}><span><b>Novo orçamento</b><small>Itens múltiplos, condições comerciais e total</small></span><strong>{open?"−":"+"}</strong></button>{open&&<div className="workflow-body sales-form">
   <div className="sales-form-grid"><label>Receita<select value={quoteRx} onChange={e=>setQuoteRx(e.target.value)} disabled={!customerId}><option value="">Sem receita</option>{customerRx.map(r=><option key={r.id} value={r.id}>{dateBR(r.date)} · {r.professional||"Profissional"}</option>)}</select></label><label>Pagamento<select value={quotePayment} onChange={e=>setQuotePayment(e.target.value)}><option value="">A combinar</option><option>PIX</option><option>DINHEIRO</option><option>DÉBITO</option><option>CRÉDITO</option><option>PARCELADO</option><option>CREDIÁRIO</option></select></label><label>Entrada<input type="number" min="0" step="0.01" value={quoteEntry} onChange={e=>setQuoteEntry(e.target.value)}/></label><div className="sales-total-box"><span>Total</span><strong>{money(total)}</strong></div></div>
   <div className="workflow-items"><div className="workflow-items-head"><b>Itens</b><button type="button" className="secondary" onClick={()=>setQuoteItems([...quoteItems,newItem()])}>+ Item</button></div>{quoteItems.map((i,idx)=><div className="workflow-item" key={idx}>{productField(quoteItems,setQuoteItems,idx)}<label>Tipo<select value={i.kind} onChange={e=>{const n=[...quoteItems];n[idx].kind=e.target.value;setQuoteItems(n)}}><option>LENTE</option><option>ARMAÇÃO</option><option>TRATAMENTO</option><option>SERVIÇO</option></select></label><label>Qtd.<input type="number" min="1" value={i.quantity} onChange={e=>{const n=[...quoteItems];n[idx].quantity=e.target.value;setQuoteItems(n)}}/></label><label>Unitário<input type="number" min="0" step="0.01" value={i.unitPrice} onChange={e=>{const n=[...quoteItems];n[idx].unitPrice=e.target.value;setQuoteItems(n)}}/></label><button type="button" className="secondary" onClick={()=>setQuoteItems(quoteItems.length===1?quoteItems:quoteItems.filter((_,x)=>x!==idx))}>×</button></div>)}</div>
   <div className="workflow-commercial"><label>Desconto<input type="number" min="0" value={quoteDiscount} onChange={e=>setQuoteDiscount(e.target.value)}/></label><label>Acréscimo<input type="number" min="0" value={quoteSurcharge} onChange={e=>setQuoteSurcharge(e.target.value)}/></label><label>Observações<textarea rows={2} value={quoteNotes} onChange={e=>setQuoteNotes(e.target.value)}/></label></div><div className="sales-actions"><button className="primary" disabled={!customerId} onClick={saveQuote}>Criar orçamento e seguir →</button></div>
  </div>}</div>}

  {stage==="PEDIDO"&&<div className="panel workflow-panel"><button className="workflow-section-head" onClick={()=>setOpen(!open)}><span><b>Novo pedido óptico</b><small>Receita, laboratório, prazo e vários produtos no mesmo pedido</small></span><strong>{open?"−":"+"}</strong></button>{open&&<div className="workflow-body sales-form">
   <div className="sales-form-grid"><label>Receita<select value={orderRx} onChange={e=>setOrderRx(e.target.value)} disabled={!customerId}><option value="">Sem receita</option>{customerRx.map(r=><option key={r.id} value={r.id}>{dateBR(r.date)} · {r.professional||"Profissional"}</option>)}</select></label><label>Laboratório<input value={laboratory} onChange={e=>setLaboratory(e.target.value)} placeholder="Laboratório parceiro"/></label><label>Prazo<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><div className="sales-total-box"><span>Total</span><strong>{money(ototal)}</strong></div></div>
   <div className="workflow-items"><div className="workflow-items-head"><b>Produtos</b><button type="button" className="secondary" onClick={()=>setOrderItems([...orderItems,newItem()])}>+ Produto</button></div>{orderItems.map((i,idx)=><div className="workflow-item" key={idx}>{productField(orderItems,setOrderItems,idx)}<label>Tipo<select value={i.kind} onChange={e=>{const n=[...orderItems];n[idx].kind=e.target.value;setOrderItems(n)}}><option>LENTE</option><option>ARMAÇÃO</option><option>TRATAMENTO</option><option>SERVIÇO</option><option>OUTRO</option></select></label><label>Olho<select value={i.eye} onChange={e=>{const n=[...orderItems];n[idx].eye=e.target.value;setOrderItems(n)}}><option value="">Ambos</option><option>OD</option><option>OE</option></select></label><label>Qtd.<input type="number" min="1" value={i.quantity} onChange={e=>{const n=[...orderItems];n[idx].quantity=e.target.value;setOrderItems(n)}}/></label><label>Unitário<input type="number" min="0" step="0.01" value={i.unitPrice} onChange={e=>{const n=[...orderItems];n[idx].unitPrice=e.target.value;setOrderItems(n)}}/></label><button type="button" className="secondary" onClick={()=>setOrderItems(orderItems.length===1?orderItems:orderItems.filter((_,x)=>x!==idx))}>×</button></div>)}</div>
   <label className="sales-wide">Observações / laboratório<textarea rows={3} value={orderNotes} onChange={e=>setOrderNotes(e.target.value)}/></label><div className="sales-actions"><button className="primary" disabled={!customerId} onClick={saveOrder}>Criar pedido e abrir laboratório →</button></div>
  </div>}</div>}

  {stage==="LABORATORIO"&&<div className="panel workflow-panel"><button className="workflow-section-head" onClick={()=>setOpen(!open)}><span><b>Fluxo do laboratório</b><small>Envio → produção → recebimento → conferência → pronto</small></span><strong>{open?"−":"+"}</strong></button>{open&&<div className="workflow-body">{loading?<div>Carregando...</div>:orders.filter(o=>["PEDIDO","AGUARDANDO_LABORATORIO","EM_PRODUCAO","RECEBIDO","CONFERENCIA","PRONTO"].includes(o.status)).map(o=><div className="workflow-order" key={o.id}><div><span className="eyebrow">PEDIDO #{o.number}</span><h3>{o.customer?.name||"Cliente"}</h3><p>{o.laboratory||"—"} · Entrega {dateBR(o.dueDate)} · {money(o.total)}</p></div><div className="workflow-order-side"><StatusBadge status={o.status}/>{next[o.status]&&<button className="primary" onClick={()=>advance(o)}>Avançar → {labels[next[o.status]]}</button>}</div></div>)}{!orders.filter(o=>["PEDIDO","AGUARDANDO_LABORATORIO","EM_PRODUCAO","RECEBIDO","CONFERENCIA","PRONTO"].includes(o.status)).length&&<div style={{padding:20,textAlign:"center",color:"var(--muted)"}}>Nenhum pedido em produção.</div>}</div>}</div>}
 </section>

}
