"use client";
import {useEffect,useState} from "react";
const stages=["AGUARDANDO_LABORATORIO","EM_PRODUCAO","RECEBIDO","CONFERENCIA","PRONTO","ENTREGUE"];
export default function Laboratorio(){
 const [rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState("");
 const load=async()=>{const r=await fetch("/api/orders");const d=await r.json();if(r.ok)setRows(d.filter((o:any)=>stages.includes(o.status)||o.status==="PEDIDO"));else setMsg(d.error||"Erro ao carregar pedidos.")};useEffect(()=>{load()},[]);
 const next=(s:string)=>({PEDIDO:"AGUARDANDO_LABORATORIO",AGUARDANDO_LABORATORIO:"EM_PRODUCAO",EM_PRODUCAO:"RECEBIDO",RECEBIDO:"CONFERENCIA",CONFERENCIA:"PRONTO",PRONTO:"ENTREGUE"} as any)[s];
 const advance=async(o:any)=>{const n=next(o.status);if(!n)return;const r=await fetch("/api/orders/"+o.id+"/status",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:n,message:"Atualização pelo laboratório"})});const d=await r.json();if(!r.ok)setMsg(d.error);else setMsg("Pedido atualizado.");load()};
 return <section className="page"><div className="page-heading"><div><span className="eyebrow">PRODUÇÃO</span><h1>Laboratório</h1><p>Fila de produção, recebimento, conferência e liberação.</p></div><button className="secondary" onClick={load}>Atualizar</button></div>{msg&&<div className="panel" style={{padding:12}}>{msg}</div>}<div className="stats">{stages.slice(0,5).map(s=><div className="stat-card" key={s}><b>{rows.filter(o=>o.status===s).length}</b><span>{s.replaceAll("_"," ")}</span></div>)}</div><div className="panel"><div className="table"><div className="row header"><span>Pedido</span><span>Cliente</span><span>Laboratório</span><span>Status</span><span>Prazo</span><span>Ação</span></div>{rows.map(o=><div className="row" key={o.id}><strong>#{o.number}</strong><span>{o.customer?.name}</span><span>{o.laboratory||"—"}</span><span>{o.status}</span><span>{o.dueDate?new Date(o.dueDate).toLocaleDateString("pt-BR"):"—"}</span><button className="link-button" onClick={()=>advance(o)}>{next(o.status)?"Avançar":"Concluído"}</button></div>)}</div></div></section>
}