"use client";
import {useEffect,useState} from "react";
type Customer={id:string;name:string;cpfCnpj?:string|null;phone?:string|null;whatsapp?:string|null;email?:string|null;birthDate?:string|null;notes?:string|null;addresses:any[];_count:any};
const empty={name:"",cpfCnpj:"",phone:"",whatsapp:"",email:"",birthDate:"",notes:""};
export default function Clientes(){
 const [rows,setRows]=useState<Customer[]>([]),[selected,setSelected]=useState<Customer|null>(null),[form,setForm]=useState(empty),[address,setAddress]=useState({label:"",street:"",number:"",complement:"",district:"",city:"",state:"SC",postalCode:""}),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[msg,setMsg]=useState("");
 const load=async()=>{const r=await fetch("/api/customers");const d=await r.json();if(r.ok)setRows(d);else setMsg(d.error||"Erro ao carregar clientes.")};
 useEffect(()=>{load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setMsg("");const r=await fetch(selected?"/api/customers/"+selected.id:"/api/customers",{method:selected?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setMsg(d.error||"Erro ao salvar.");return}setOpen(false);setSelected(null);setForm(empty);await load()};
 const edit=(c:Customer)=>{setSelected(c);setForm({name:c.name,cpfCnpj:c.cpfCnpj||"",phone:c.phone||"",whatsapp:c.whatsapp||"",email:c.email||"",birthDate:c.birthDate?c.birthDate.slice(0,10):"",notes:c.notes||""});setOpen(true)};
 const addAddress=async()=>{if(!selected)return;const r=await fetch("/api/customers/"+selected.id+"/addresses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(address)});if(r.ok){setAddress({label:"",street:"",number:"",complement:"",district:"",city:"",state:"SC",postalCode:""});const d=await fetch("/api/customers/"+selected.id).then(x=>x.json());setSelected(d);setRows(x=>x.map(c=>c.id===d.id?d:c))}else setMsg((await r.json()).error||"Erro ao salvar endereço.")};
 const filtered=rows.filter(c=>(c.name+" "+(c.cpfCnpj||"")+" "+(c.phone||"")).toLowerCase().includes(search.toLowerCase()));
 return <section className="page"><div className="page-heading"><div><span className="eyebrow">CADASTRO</span><h1>Clientes</h1><p>Cadastro, contatos, endereços, histórico, receitas, pedidos, vendas e financeiro.</p></div><button className="primary" onClick={()=>{setSelected(null);setForm(empty);setOpen(true)}}>+ Novo cliente</button></div>
 {msg&&<div className="panel" style={{padding:12,color:"#a33"}}>{msg}</div>}
 <div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, CPF/CNPJ ou telefone..."/></div>
 <div className="panel"><div className="table"><div className="row header"><span>Cliente</span><span>Documento</span><span>Telefone</span><span>Pedidos</span><span>Receitas</span><span></span></div>{filtered.map(c=><div className="row" key={c.id}><strong>{c.name}</strong><span>{c.cpfCnpj||"—"}</span><span>{c.whatsapp||c.phone||"—"}</span><span>{c._count?.orders??0}</span><span>{c._count?.prescriptions??0}</span><button className="link-button" onClick={()=>edit(c)}>Abrir</button></div>)}</div></div>
 {open&&<div className="panel" style={{padding:20}}><div className="panel-heading" style={{padding:0,marginBottom:15}}><div><h2>{selected?"Editar cliente":"Novo cliente"}</h2></div><button className="secondary" onClick={()=>setOpen(false)}>Fechar</button></div>
 <form onSubmit={save} style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>{Object.entries(form).map(([k,v])=><label key={k} style={{fontSize:10,display:"grid",gap:5}}>{k}<input value={v} onChange={e=>setForm({...form,[k]:e.target.value})} style={{padding:9,border:"1px solid var(--line)",borderRadius:7}} /></label>)}<button className="primary" type="submit">Salvar cliente</button></form>
 {selected&&<><h3 style={{fontSize:12,marginTop:25}}>Endereços</h3>{selected.addresses.map(a=><div key={a.id} style={{fontSize:10,padding:"8px 0",borderTop:"1px solid var(--line)"}}>{[a.label,a.street,a.number,a.complement,a.district,a.city,a.state,a.postalCode].filter(Boolean).join(", ")}</div>)}<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:10}}>{Object.entries(address).map(([k,v])=><input key={k} placeholder={k} value={v} onChange={e=>setAddress({...address,[k]:e.target.value})} style={{padding:8,border:"1px solid var(--line)",borderRadius:7}}/>)}<button className="secondary" onClick={addAddress}>Adicionar endereço</button></div><h3 style={{fontSize:12,marginTop:25}}>Histórico</h3><p style={{fontSize:10,color:"var(--muted)"}}>Pedidos: {selected._count?.orders??0} · Vendas: {selected._count?.sales??0} · Receitas: {selected._count?.prescriptions??0} · Contas: {selected._count?.accounts??0}</p></>}
 </div>}</section>
}
