"use client";
import {useEffect,useState} from "react";
import {useRealtimeRefresh} from "@/lib/use-realtime-refresh";
type Customer={id:string;name:string;cpfCnpj?:string|null;phone?:string|null;whatsapp?:string|null;email?:string|null;birthDate?:string|null;notes?:string|null;addresses:any[];prescriptions?:any[];orders?:any[];sales?:any[];accounts?:any[];_count:any};
const empty={name:"",cpfCnpj:"",phone:"",whatsapp:"",email:"",birthDate:"",notes:""};
const rxEmpty={professional:"",validUntil:"",odSphere:"",odCylinder:"",odAxis:"",odAdd:"",odDnp:"",odHeight:"",oeSphere:"",oeCylinder:"",oeAxis:"",oeAdd:"",oeDnp:"",oeHeight:"",pdTotal:"",notes:""};
export default function Clientes(){
 const [rows,setRows]=useState<Customer[]>([]),[selected,setSelected]=useState<Customer|null>(null),[form,setForm]=useState(empty),[address,setAddress]=useState({label:"",street:"",number:"",complement:"",district:"",city:"",state:"SC",postalCode:""}),[rx,setRx]=useState(rxEmpty),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[msg,setMsg]=useState("");
 const load=async()=>{const r=await fetch("/api/customers",{cache:"no-store"});const d=await r.json();if(r.status===401){window.location.href="/login";return}if(r.ok)setRows(d);else setMsg(d.error||"Erro ao carregar clientes.")};
 useEffect(()=>{load()},[]);
 useRealtimeRefresh(load,20000);
 const detail=async(id:string)=>{const r=await fetch("/api/customers/"+id);const d=await r.json();if(r.ok){setSelected(d);setForm({name:d.name,cpfCnpj:d.cpfCnpj||"",phone:d.phone||"",whatsapp:d.whatsapp||"",email:d.email||"",birthDate:d.birthDate?d.birthDate.slice(0,10):"",notes:d.notes||""})}else setMsg(d.error||"Erro ao abrir cliente.")};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setMsg("");const r=await fetch(selected?"/api/customers/"+selected.id:"/api/customers",{method:selected?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(r.status===401){window.location.href="/login";return}if(!r.ok){setMsg(d.error||"Erro ao salvar.");return}setOpen(false);setSelected(null);setForm(empty);await load();await detail(d.id)};
 const addAddress=async()=>{if(!selected)return;const r=await fetch("/api/customers/"+selected.id+"/addresses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(address)});if(r.ok){setAddress({label:"",street:"",number:"",complement:"",district:"",city:"",state:"SC",postalCode:""});await detail(selected.id);await load()}else setMsg((await r.json()).error||"Erro ao salvar endereço.")};
 const addRx=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;const r=await fetch("/api/prescriptions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...rx,customerId:selected.id})});const d=await r.json();if(!r.ok){setMsg(d.error||"Erro ao registrar receita.");return}setRx(rxEmpty);await detail(selected.id);setMsg("Receita registrada.")};
 const filtered=rows.filter(c=>(c.name+" "+(c.cpfCnpj||"")+" "+(c.phone||"")+" "+(c.whatsapp||"")).toLowerCase().includes(search.toLowerCase()));
 const fields=(obj:any,exclude:string[]=[])=>(Object.entries(obj).filter(([k])=>!exclude.includes(k)));
 return <section className="page">
 <div className="page-heading"><div><span className="eyebrow">CADASTRO</span><h1>Clientes</h1><p>Cadastro, contatos, endereços, receitas e histórico comercial.</p></div></div>
 <div style={{display:"flex",justifyContent:"flex-end",marginTop:-6}}><button className="primary" onClick={()=>{setSelected(null);setForm(empty);setOpen(true)}}>+ Novo cliente</button></div>
 {msg&&<div className="panel" style={{padding:12,color:"#a33"}}>{msg}</div>}
 <div className="panel" style={{padding:20,marginTop:12}}><div className="panel-heading" style={{padding:0,marginBottom:15}}><div><h2>{selected?"Editar cliente":"Cadastro de cliente"}</h2><p style={{fontSize:11,color:"var(--muted)"}}>{selected?"Altere os dados e salve a atualização.":"Preencha os dados para adicionar um novo cliente à lista."}</p></div><button className="secondary" onClick={()=>{setOpen(false);setSelected(null)}}>Fechar</button></div><form onSubmit={save} style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>{fields(form).map(([k,v])=><label key={k} style={{fontSize:10,display:"grid",gap:5}}>{k}<input type={k==="birthDate"?"date":k==="email"?"email":"text"} value={String(v)} onChange={e=>setForm({...form,[k]:e.target.value})} style={{padding:9,border:"1px solid var(--line)",borderRadius:7}} /></label>)}<button className="primary" type="submit">Salvar cliente</button></form></div>
 <div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, CPF/CNPJ ou telefone..."/></div>
 <div className="panel"><div className="table"><div className="row header"><span>Cliente</span><span>Documento</span><span>Telefone</span><span>Pedidos</span><span>Receitas</span><span></span></div>{filtered.map(c=><div className="row" key={c.id}><strong>{c.name}</strong><span>{c.cpfCnpj||"—"}</span><span>{c.whatsapp||c.phone||"—"}</span><span>{c._count?.orders??0}</span><span>{c._count?.prescriptions??0}</span><button className="link-button" onClick={()=>detail(c.id)}>Abrir</button></div>)}</div></div>
 {selected&&<div className="panel" style={{padding:20,marginTop:12}}><div className="panel-heading" style={{padding:0,marginBottom:15}}><div><h2>{selected.name}</h2><p style={{fontSize:10,color:"var(--muted)"}}>{selected.cpfCnpj||"Sem CPF/CNPJ"} · {selected.phone||selected.whatsapp||"Sem telefone"}</p></div><div style={{display:"flex",gap:8}}><button className="secondary" onClick={()=>setOpen(true)}>Editar</button><button className="secondary" onClick={()=>setSelected(null)}>Fechar</button></div></div>
 <h3 style={{fontSize:12}}>Endereços</h3>{selected.addresses.map(a=><div key={a.id} style={{fontSize:10,padding:"8px 0",borderTop:"1px solid var(--line)"}}>{[a.label,a.street,a.number,a.complement,a.district,a.city,a.state,a.postalCode].filter(Boolean).join(", ")}</div>)}<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:10}}>{fields(address).map(([k,v])=><input key={k} placeholder={k} value={String(v)} onChange={e=>setAddress({...address,[k]:e.target.value})} style={{padding:8,border:"1px solid var(--line)",borderRadius:7}}/>)}<button className="secondary" onClick={addAddress}>Adicionar endereço</button></div>
 <h3 style={{fontSize:12,marginTop:25}}>Receitas</h3>{(selected.prescriptions||[]).map((p:any)=><div key={p.id} style={{fontSize:10,padding:"8px 0",borderTop:"1px solid var(--line)"}}>Data: {new Date(p.date).toLocaleDateString("pt-BR")} · Profissional: {p.professional||"—"} · OD {p.odSphere??"—"} / {p.odCylinder??"—"} · OE {p.oeSphere??"—"} / {p.oeCylinder??"—"}{p.validUntil?" · válida até "+new Date(p.validUntil).toLocaleDateString("pt-BR"):""}</div>)}
 <form onSubmit={addRx} style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:7,marginTop:10}}><input placeholder="Profissional" value={rx.professional} onChange={e=>setRx({...rx,professional:e.target.value})}/><input type="date" value={rx.validUntil} onChange={e=>setRx({...rx,validUntil:e.target.value})}/>{["odSphere","odCylinder","odAxis","odAdd","odDnp","odHeight","oeSphere","oeCylinder","oeAxis","oeAdd","oeDnp","oeHeight","pdTotal"].map(k=><input key={k} placeholder={k} value={(rx as any)[k]} onChange={e=>setRx({...rx,[k]:e.target.value})}/>) }<button className="primary" type="submit">Registrar receita</button></form>
 <h3 style={{fontSize:12,marginTop:25}}>Histórico comercial</h3><p style={{fontSize:10,color:"var(--muted)"}}>Pedidos: {selected.orders?.length??0} · Vendas: {selected.sales?.length??0} · Contas: {selected.accounts?.length??0}</p>
 {(selected.orders||[]).slice(0,10).map((o:any)=><div key={o.id} style={{fontSize:10,padding:"8px 0",borderTop:"1px solid var(--line)"}}>Pedido #{o.number} · {o.status} · R$ {Number(o.total).toFixed(2)} · {new Date(o.createdAt).toLocaleDateString("pt-BR")}</div>)}
 {(selected.sales||[]).slice(0,10).map((s:any)=><div key={s.id} style={{fontSize:10,padding:"8px 0",borderTop:"1px solid var(--line)"}}>Venda #{s.number} · R$ {Number(s.total).toFixed(2)} · {new Date(s.createdAt).toLocaleDateString("pt-BR")}</div>)}
 {(selected.accounts||[]).slice(0,10).map((a:any)=><div key={a.id} style={{fontSize:10,padding:"8px 0",borderTop:"1px solid var(--line)"}}>Conta {a.type==="RECEBER"?"a receber":"a pagar"} · {a.description} · R$ {Number(a.amount-a.paidAmount).toFixed(2)} · {a.status}</div>)}
 </div>}</section>
}
